### ISSUE TITLE
anvi-load-sqm.py returns IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by nebfield** [jtamames/SqueezeMeta#100]
Hello,

I was having some issues with loading SqueezeMeta results into anvi'o but fixed them thanks to your help (#70, #72).

I'm having a new error with a different dataset. Running this:

```
python3 ~/.conda/envs/SqueezeMeta1.1/SqueezeMeta/utils/anvio_utils/anvi-load-sqm.py -p control -o anvio_control --num-threads 40 --min-contig-length 10000 --run-scg-taxonomy --run-HMMS
```

Produces this error message:

```
IndexError: list assignment index out of range
There must be some problem with "anvi-gen-contigs-database -f /data2/wp6/pilot_metagenomic_run/control/results/sqm2anvio/control_anvio_contigs.txt -n control -o anvio_control/CONTIGS.db --external-gene-call /data2/wp6/pilot_metagenomic_run/control/results/sqm2anvio/control_anvio_genes.txt --ignore-internal-stop-codons".
It's better to stop and check it
```

Full error message:

```
Traceback (most recent call last):
File "/home/ben/.conda/envs/anvio/bin/anvi-gen-contigs-database", line 54, in <module>
    a.create(args)
  File "/home/ben/.conda/envs/anvio/lib/python3.6/site-packages/anvio/dbops.py", line 3640, in create
    nt_position_info_list = self.compress_nt_position_info(contig_length, genes_in_contig, genes_in_contigs_dict)
  File "/home/ben/.conda/envs/anvio/lib/python3.6/site-packages/anvio/dbops.py", line 3733, in compress_nt_position_info
    nt_position_info_list[nt_position] = 8
```
Thanks for your help 😄

**Comment by fpusan** [comment]
The error is happening within anvi'o, and it seems related to this particular dataset.

We will try to reproduce it. We would need
1) Your anvi'o version
2) The `/data2/wp6/pilot_metagenomic_run/control/results/sqm2anvio/control_anvio_contigs.txt` file
3) The `/data2/wp6/pilot_metagenomic_run/control/results/sqm2anvio/control_anvio_genes.txt` file

**Comment by jtamames** [comment]
Closing by inactivity

**Comment by okcoskun** [comment]
Hello, 

I got the same error from "anvi-load-sqm.py". I am using anvio-6.2. In case, you would like to reproduce, I can send you the files. I am not sure if @nebfield found a solution for it? 

Thanks in advance.

**Comment by fpusan** [comment]
Sure, please send us the files.
Does it also happen with the test dataset?

**Comment by okcoskun** [comment]
Dear Fernando,

I have sent an e-mail to you. I am looking forward to hearing from you :).

Cheers

**Comment by fpusan** [comment]
Will look into it!

**Comment by meren** [comment]
The problem seems to be related to anvi'o. It looks like it is due to an external gene call that does not respect the actual boundaries of the contig (which seems to be only 302 nts with two genes).

I say this is two folds: one, there is likely a bug at the level of gene calling and/or translating gene caller output to external gene calls, and two, anvi'o fails its users by not sanity checking external gene calls given the set of contigs rigorously.

I'll keep an eye on the issue.

Best wishes,

**Comment by fpusan** [comment]
@meren thanks for chiming in! Your diagnostic is correct, the gene is longer than the contig. We should also make a bigger effort to double-check that our scripts produce sane outputs.

@okcoskun, we will try to reproduce the error. Can you send us the following files?
`/path/to/your/project/SqueezeMeta_conf.pl`
`/path/to/your/project/results/01.*.fasta`
`/path/to/your/project/results/03.*.gff`

And if there's any file in the results folder starting with `08`, also send us the `/path/to/your/project/results/08.*.gff`file.

**Comment by fpusan** [comment]
Can reproduce with the assembly you sent me. The issue does not happen in the SqueezeMeta to anvi'o interface, but during the generation of the gff file. I have a general idea of what could be happening, hopefully tomorrow we'll have an explanation/solution.

**Comment by fpusan** [comment]
Hopefully solved as of 6ae7cb2a7afdf24b12e613fe754c01d103331ec9.

The issue was caused by a dire and luckily infrequent combination of three problems:
1) aragorn predicted a mtRNA starting from a negative position (-69).
2) Prior to running prodigal for detecting protein-coding ORFs, SqueezeMeta masks RNA-coding genes with Ns. Due to a now patched oversight on our part the negative index in aragorn's output made the SQM script add 69 Ns at the end of the contig in the temporary file we give to prodigal, increasing its size from 302 to 372.
3) We run prodigal using the `-m` flag, which according to the documentation serves to "treat runs of N as masked sequence; don't build genes across them". In spite of this, Prodigal predicted a gene from positions 2 to 370, which included most of the Ns. We'll have to look into that.

The original assembly file (from which we later build the contigs file for anvi'o) remained unchanged, with the contig having the correct length. But the gff file with the prodigal prediction (from which we later build the genes file for anvi'o) referred to those bugged positions, hence the error in `anvi-gen-contigs-database`.

So in order to fix your problem:

1) Safest option would be to replace your `02.rnas.pl` script for the patched one and restart from step 2.

2) Quickest option would be to remove contigs `megahit_548525` and `megahit_2206564` (AFAIK the only two occurrences of this issue in your dataset) from your SqueezeMeta results files and re-run `anvi-load-sqm.py`.

Let me know if this works for you!

**Comment by okcoskun** [comment]
Thank you Fernando, I will take my holiday next week and the problem was that It took 8 days to run (MaxBin was too slow), but I will try to apply the shortest option today. I will let you know. I have limited understanding on this topic, but wouldn't the anvi-load-sqm script be optimal if the scripts first selects the contigs greater than 2500 bp and then proceed to create CONTIG.db?

Cheers

Ömer

**Comment by ggnatalia** [comment]
The –min-contig-length option which is in the anvi-load-sqm.py script is used when calling the anvi-profile step from anvio. As far as we know, anvio applies length filtering in this step, but not in the generation of the CONTIGS.db. 

From our experience, the anvi-profile step takes more time than the anvi-gen-contigs-database, so that it shouldn’t make a big difference to filter those contigs before.

Cheers,
Natalia
