### ISSUE TITLE
sqmreads2tables.py and combine-sqn-tables Error

### ISSUE THREAD

**Issue by EricRaes** [jtamames/SqueezeMeta#118]
Hello,

I ran sqm_reads on 150bp paired reads on 12 individual samples. All went smoothly. I then used the 'sqmreads2tables.py' script to make the tabular outputs for each sample: 

Using: ~/SqueezeMeta/utils/sqmreads2tables.py ~/sqm2reads_sampleA/  ~/Tables_sampleA/
          ~/SqueezeMeta/utils/sqmreads2tables.py ~/sqm2reads_sampleB/  ~/Tables_sampleB/
Which worked fine.

Yet, when I try to combine the tabular outputs using "combine-sqm-tables.py "

Using: ~/SqueezeMeta/utils/combine-sqm-tables.py ~/Tables_sampleA/ ~/Tables_sampleB/ -o Combined_A_B --sqmreads

I received the following error: 

File "~/SqueezeMeta/utils/combine-sqm-tables.py", line 312, in <module>
    main(parse_args())
  File "~/SqueezeMeta/utils/combine-sqm-tables.py", line 128, in main
    raise Exception('Path "{}" does not exist, or does not contain a valid SQM project'.format(projPath))
Exception: Path "~/Tables_sampleA/" does not exist, or does not contain a valid SQM project

However, when use 'combine-sqm-tables.py', using:

~/SqueezeMeta/utils/combine-sqm-tables.py ~/sqm2reads_sampleA/ ~/sqm2reads_sampleB/ -o output_dir_A_B --sqmreads

all works fine, within the sqm_reads sample folder I get a "results" folder and I get an output_dir_A_B with the combined files.

Would you have an idea why the 'combine-sqm-tables.py' fails in combining the tabular formats but not when I direct the path to the sqm_reads output?

Many thanks!
Best regards,
Eric

I've attached the combine-sqm-tables script if that would be useful.
[combine-sqm-tables.zip](https://github.com/jtamames/SqueezeMeta/files/4790385/combine-sqm-tables.zip)

**Comment by EricRaes** [comment]
as a quick follow up question. When I ran the 'sqmreads2tables.py' as a batch run for a single sample it cut out (for some samples) due to memory requirements, even after I requested 100Gb. Would you have an idea (ballpark) what the memory allocation necessary would be for a single sample to run 'sqmreads2tables.py'? Sequencing depth varied between ~50M-120M reads.
Many thanks!!
Best regards,
Eric

**Comment by fpusan** [comment]
Regarding your first question, the script checks that the input folders are valid SQM or SQM reads projects by design. As documented, the input directories must be whole SQM/SQMreads projects, rather than just the tables directories.

Regarding your second question, I don't have a clear answer. The `sqmreads2tables.py` script peak memory usage is likely to come during the taxonomy aggregation part. So to ballpark it I would:

1) Go to the largest sample (there is one directory per sample inside the SQMreads output directory).
2) Calculate the combined size of the `*.tax.wranks` and `*tax_nofilter.wranks` files in that directory,
3) Multiply that by 1.5 (it creates an additional third dictionary combining data from those two files).
4) Multiply that by an arbitrary constant expressing the memory overhead of storing information in python dictionaries. I just tested loading a 1.3 Gb file into python, and the peak memory usage of the process was of 2.7 Gb, so that constant would be c.a. 2 (yes, naive python is really not memory-efficient).

Hope this helps. Right now the `sqmreads2tables.py` is coded in a very straightforward way, and I might be able to optimize memory usage if required.

**Comment by EricRaes** [comment]
Thanks Fernando!
