### ISSUE TITLE
loadSQM combined project

### ISSUE THREAD

**Issue by kassammohamed** [jtamames/SqueezeMeta#120]
Hello,

I have combined two Sequential projects using combine-sqm-tables.py.
When I am loading with loadSQM I am getting the error below
`loadSQM("COMBINED/")
Error in loadSQM("COMBINED/") :
  Directory "COMBINED/" does not seem to contain a valid SqueezeMeta project`

**Comment by fpusan** [comment]
Second issue with this question this morning! Just as in #119, use the `loadSQMlite` function instead. Or load each project independently into SQM with the `loadSQM` function.

Also, if your computational resources allow it, it is preferable to run SqueezeMeta in the `coassembly`, `merged` or `seqmerge` modes rather than using the sequential mode and then combining the results with `combine-sqm-tables.py`. Taxonomic and functional profiles will be similar in all cases, but the first three options work with a common assembly for all your samples, which improves binning and allows you to use `loadSQM` in the combined results.

**Comment by kassammohamed** [comment]
Hi,

I tried to combine using `combineSQM` with SQMtools in R, I am getting this error:
`combineSQM(SQM1,SQM2)
Error in combineSQM_(SQM1, SQM2, tax_source, trusted_functions_only, ignore_unclassified_functions,  :
  identical(colnames(SQM1$orfs$table), colnames(SQM2$orfs$table)) is not TRUE`

Thanks

**Comment by fpusan** [comment]
Hi!

Are you perhaps trying to combine SQM objects coming from different projects?

If so, this is not supported by the `combineSQM` function. The idea would be that you can generate different subsets from the same project using `subsetFun` or `subsetTax` and then can combine them using `combineSQM`. I just realized this is not documented anywhere, I'll correct that ASAP.

If you want to combine results from different projects, you can generate combined tables using the script `SqueezeMeta/utils/combine-sqm-tables.py` (which you are already familiar with). This will generate aggregated functional and abundance tables, but not combined ORF, contigs or bins tables.

What are you trying to achieve? Perhaps I can help you find the best solution.

**Comment by jtamames** [comment]
Closing by inactivity
