### ISSUE TITLE
Export the annotated sequences with the tax file from a sqm_reads run?

### ISSUE THREAD

**Issue by EricRaes** [jtamames/SqueezeMeta#129]
Hello again :-),

Two quick questions and apologies in advance if these are trivial:

1) is there a way to export a representative annotated sequence with the taxonomy file? (so you would kinda get an ASV table)
2) is there a possibility to export the non-annotated sequences ?

Many thanks for your help and suggestions!
Best regards,
Eric

**Comment by fpusan** [comment]
Hi,

1) The term "representative sequences" implies some sort of clustering (note that ASVs ARE clusters, only that the clustering criterion is identity instead of an arbitrary distance threshold). This only makes sense when all the reads come from the same gene (as in 16S rRNA). SqueezeMeta deals with shotgun metagenomes rather than amplicons, read come from random regions of the (meta)genomes, and they are classified based on homology to full proteome databases. So reads classified into the same taxon are not expected to have any kind of homology between themselves, thus are not clusterizable. 

If you are interested in performing a fine-grain taxonomic characterization of your samples, consider using amplicons.

**Comment by fpusan** [comment]
... continuing here, as I closed the issue by mistake.

2. Regarding the non-annotated sequences, they are not tracked by SQMtools in any way. The output directory of sqm_reads contains an output file `<project_name>.out.allreads` with all the annotated reads . So all the reads that are in the original fastq files but not in that output file will be non-annotated.
