### ISSUE TITLE
taxonomic information - question

### ISSUE THREAD

**Issue by bioinfo17** [jtamames/SqueezeMeta#133]
Hi,

In the manual and the manuscript, it's mentioned that taxonomic classification can be applied both at gene and contig level. Where can I find the resulting files?

the 11.*.mcount file has the taxonomic classification at the contig level - what does the accumulated contig size refer to please?

Many thanks

**Comment by jtamames** [comment]
Hello!
The `06.*.wranks` files in the results directory store the taxonomic classification for individual genes. You will find two files, one of which is labelled "noidfilter". That one is dropping the identity thresholds for taxonomic annotation (see the wiki for a [detailed discussion on this](https://github.com/jtamames/SqueezeMeta/wiki/A-discussion-on-taxonomic-annotation-and-the-meaning-of-disparity-values-of-contigs)). We used the one with identity filters for producing the annotation of the contigs. Also the `13.*.orftable` file lists the taxonomy of the individual genes.
Regarding the accumulated contig size in the mcount file, that refers to the sum of lengths of all contigs for that particular taxon. Notice that this does not necessarily corresponds to the abundance or importance of the taxon in the microbiome. For instance, assume that there is one genus with a very abundant species in your samples. The accumulated contig size will be close to the genomic size of that species, whereas for a genus having multiple species not that abundant, accumulated contig size can be higher, corresponding to the sum of the contributions of the different species.

Best,
Javier

**Comment by bioinfo17** [comment]
thanks for the answer. I also noticed in the taxonomic counts file the numbers don't tally up, pls see example below: 
for example at the order level, the counts for family, genus and species should add up isn't it? I'm unsure whether to take the counts at species level for further statistical analysis or is there are a way that would generate all the taxonomic lineages just in one line and summarize all the counts together. Your advice on this will be much appreciated.

		sample1 reads	sample2 reads
o	k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Pseudomonadales	46	45
f	k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Pseudomonadales;f_Moraxellaceae	33	25
g	k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Pseudomonadales;f_Moraxellaceae;g_Moraxella	11	10
s	k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Pseudomonadales;f_Moraxellaceae;g_Moraxella;s_Moraxella osloensis	11	10
g	k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Pseudomonadales;f_Moraxellaceae;g_Acinetobacter	4	2
g	k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Pseudomonadales;f_Pseudomonadaceae;g_Pseudomonas	13	20
f	k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Pseudomonadales;f_Pseudomonadaceae	13	20

**Comment by jtamames** [comment]
Hello!
The counts for a particular ranks not necessarily correspond to the sum of the counts of all ranks below it. In your example, the counts for family Moraxellaceae is 33 in the first dataset, but the counts for all genera belonging to Moraxellaceae just add to 26. The reason is that we are using a last common ancestor (LCA) for the assignment that can classify ORFs at intermediate ranks. That is, the 7 missing counts above correspond to ORFs that were classified to family Moraxellaceae, but it was not possible to classify them at the genus level because of lack of evidence. You can find information on the functioning of the LCA algorithm in the last section of the manual.
Notice that the counts for the family Moraxellaceae include ORFs classified to that family AND all ranks below belonging to this family. The rationale of this is that you can have a neat table of your desired rank simply by using a grep statement. For instance, if you decide you want to work at the family level, you just need to do `egrep ">f" file.mcount` and you will have it right away. And of course, using the `sqm_tools` package simplifies the work further. 

I cannot understand exactly your question about all the taxonomic lineages just in one line, I am sorry. Could you please put an example of your desired output?

Best,
Javier

**Comment by bioinfo17** [comment]
It all makes sense now, many thanks for answering.
