### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by gdauria** [jtamames/SqueezeMeta#176]
Dear Javier, Fernando and Natalia, first of all I would like to congratulate with the incredible work you are doing.
I have a couple of suggestions for new features.
1) Adding the possibility to choose the contigs ID instead of using automatic megahit_# (in case of using megahit assembler).
2) The possibility to have a final Genbank file with a format similar to the one coming out from prokka. This can be useful as input for Roary searching for orthologs (as well as for data sharing).
3) Including KEGG, COG PFAM features in 08 GFF file.
4) Adding the possibility to start a blank project only creating necessary folders and files for skipping initial steps in case I provide contigs or annotations from outside SQM.
I do not know if it is possible, but I would like to thank you in advance for your efforts.

Bests

Giuseppe

**Comment by jtamames** [comment]
Dear Giuseppe

Thanks a lot for the suggestions. All of them seem doable with no much effort. I will put these in future development versions.
Best,
Javier

**Comment by jtamames** [comment]
Hello
Some of these features are already available, and you should clone the appropriate scripts from the development branch of this repo.

1: Custom contig names: Download `SqueezeMeta.pl` and all `01` scripts. Now you have the -contigid option when running `SqueezeMeta.pl`:
    `-contigid <string>: Nomenclature for contigs (Default: assembler´s name)`

2: That is a difficult one because of the way we are generating the tables for not using too much RAM memory that could crash the run. I still have to think how to do this.

3: Also in progress. What kind of tag would you put to specify the functions in the gff?

4. Already  implemented in `SqueezeMeta.pl`. Now there is the `--empty` flag that will create an a empty project with all needed conf files. The run must be specified as always (that is, you need a samples file pointing to existing sequence files, even if these can also be empty files)

Best,
Javier
