### ISSUE TITLE
Regarding functional annotation 

### ISSUE THREAD

**Issue by razz1618** [jtamames/SqueezeMeta#187]
Hi,  I read through the manual but didn't quite got the answer. My query is How squeezemeta assigns taxonomy to a particular function and what are the chances that it is correctly assigned. It is hard and with the current state of bioinformatics, nearly impossible to build MAGs corresponding to each species within the metagenome. I n this case, How to make sure that the functionally assigned taxons (without bins)  is correct. For example, 

**k_Bacteria;p_Proteobacteria;c_Alphaproteobacteria;o_Rhodobacterales;f_Rhodobacteraceae	K06204*	DnaK suppressor protein	Cellular Processes**

How to make sure that this particular gene really exist in the mentioned taxon?

**Comment by fpusan** [comment]
>My query is How squeezemeta assigns taxonomy to a particular function and what are the chances that it is correctly assigned.

SqueezeMeta assigns taxonomy and function independently. We use homology to NCBI's nr database for taxonomy annotations (with all the bells and chimes that we discuss in the manual and in other answers here) and homology to the KEGG and COG (and alternatively additional databases provided by the user) databases for functional annotation. The actual algorithm is described in the manual, in the _The fun3 algorithm_ subsection. Finally, we also use HMM searches against the PFAM database for functional annotation.

Linking taxonomy and function is simply a matter of selecting the ORFs from a given function and looking at their taxonomy.

>How to make sure that this particular gene really exist in the mentioned taxon?

You really can't be sure, at least by using metagenomics. As we discussed in other thread, we are quite confident in our taxonomic predictions (SqueezeMeta is conservative, and it tends to underpredict taxonomy for lower taxonomic ranks, but when it predicts something it's usually right). The case for proteins is however more complicated.

The critical issue here (which IMO is not discussed enough) is that the fact that a predicted protein is a reasonable homolog of another protein in the database does not guarantee that it will perform the same biochemical function in nature. The problem becomes worse when we consider that the proteins in the reference database (which we use to assign our own proteins to functions) might be poorly annotated themselves.

We (and of course other developers too) take great efforts to make our algoriths as robust as possible, but results should be interpreted as "possibilities" rather than certainties. Of course if an ORF in your metagenome has a 100% homology to an extensively characterized protein in _E. coli_ , you can be quite sure that its performing the same function. But this scenario is an exception rather than the norm, since reference databases are incomplete and proteins in databases are not always well characterized.

So if you _really_ want to confrim that a given function is associated to a given taxa in your samples, first isolate the taxon, then purify the protein, then do a biochemical assay to characterize its function. Of course almost no one wants to do that anymore, since meta'omics are faster, fancier and way less depressing than good old biochemistry. It does however not substitute for experimental work (although we'd like to pretend it does), and results should always be taken with a healthy grain of salt.
