### ISSUE TITLE
Regarding Anvio's visualization 

### ISSUE THREAD

**Issue by razz1618** [jtamames/SqueezeMeta#189]
Hi,
I have created profile.db, contigs.db contig_taxonomy.txt. Is it possible to load all bins with all functions (my data is not huge) into anvio interactive without filtering the data? if yes, how to do that?

Secondly, can I combine multiple project bins and load into ANVIO for visualization?

In my bin table, some bins are classified till sps. level while some are classified only at higher classification level (such as class, family, order). Why is it so? If I am not wrong these are almost complete genomes that can be extracted from the sample, then why it is not classified well (as the contig/bin will have much information for required classification)/

**Comment by ggnatalia** [comment]
Hi!

**I have created profile.db, contigs.db contig_taxonomy.txt. Is it possible to load all bins with all functions (my data is not huge) into anvio interactive without filtering the data? if yes, how to do that?**

Our approach, is to run the anvi-filter script, but with a filter that includes all contigs:

    path/to/SqueezeMeta/utils/anvio_utils/anvi-filter-sqm.py -c <project>/results/anvio/CONTIGS.db -p <project>/results/anvio/PROFILE.db -t <project>/results/anvio/<project>_anvio_contig_taxonomy.txt -q PHYLUM != 'Hello' -o <project>/results/anvio/allContigs

You can check it when the script is running, due to it tells you how many splits are selected from the total number of splits. The anvi-filter script creates a newick tree with the order of your contigs based on the taxonomy. We use it to give an order to your contigs, so that you can run anvi-interactive without any problem.

After doing that, run within anvio directory: 

     anvi-interactive -c CONTIGS.db -p PROFILE.db -t allContigs/Taxonomy.nwk


**Secondly, can I combine multiple project bins and load into ANVIO for visualization?**

We don't support the combination of different projects from SQM in anvio. We recommend the use of the R package SQMtools to explore data (and we have added this option to the package). If you are interested in working with anvi'o, feel free to visit their webpage (http://merenlab.org/software/anvio/) and see all their options. You can always run anvi'o pipeline from the beginning (without SQM results) or write some scripts to parse SQM data into tables that are required by anvio (which is in fact what anvi-load-sqm does).

**In my bin table, some bins are classified till sps. level while some are classified only at higher classification level (such as class, family, order). Why is it so? If I am not wrong these are almost complete genomes that can be extracted from the sample, then why it is not classified well (as the contig/bin will have much information for required classification)/**

I cannot help you much with this question. Maybe @jtamames can help you with this.

**Comment by jtamames** [comment]
The procedure for contig and bin annotation by consensus is explained in the manual. Please refer to the last section (explanation of SqueezeMeta algorithms)

**Comment by jtamames** [comment]
Closing issue, feel free to reopen.

**Comment by razz1618** [comment]
@ggnatalia Thanks for the explanation and command. That worked smoothly. My aim to integrate the results into ANVIO is to visualize the bins (with taxonomy and functional annotation) . **What filter/query I should use so that I can just separate all the bins(along with its annotation) into anvio?**

**Comment by ggnatalia** [comment]
Hi,

You can visualize bin by bin with its annotations using the interface of anvi-refine, which aims to facilitate manually bins curation. 

    anvi-refine -c CONTIGS.db -p PROFILE.db -C DAS -b <bin_name>

If you need to visualize other information, you can always parse SQM results and build input tables following anvio instructions  and add them to anvio databases (http://merenlab.org/2016/02/27/the-anvio-interactive-interface/#1-data-types-and-input-files).
