### ISSUE TITLE
Enhance by skipping eukaryotic databases?

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#191]
Would it be possible to add the ability to annotate assemblies/reads to prokaryotic databases only? This would be an awesome feature as I'm not really interested in the eukaryotic data.

**Comment by jtamames** [comment]
Hello
You could always replaced the shipped database with your new one: create a new database a a fasta file, format it and name it as nr.dmnd in the database directory. It should work as long as you keep the GenBank accession numbers.

BUT, (and this is the reason that we don´t provide a tool to do this), I cannot recommend you to do so because you can make many incorrect assignments. For instance, suppose you have an eukaryotic gene with bacterial homologs. If you use a prokaryotic database you will only see the bacterial homologs, missing the eukaryotic ones, and as a result you will wrongly annotate it as a bacterial gene. This is why we recommend to use and try to provide the most complete database available. Even if you are not interested in eukaryotic data, you will probably have eukaryotic organisms (also coming from possible contaminations, e.g, human) in your dataset that you would not want to confound with others.

Best,
Javier

**Comment by mradz19** [comment]
Hi Javier,

How does squeezemeta decide whether to assign an annotation as eukaryotic or prokaryotic if they are homologs?

Is it based on mapping accuracy?

**Comment by jtamames** [comment]
Hello
SqueezeMeta uses a LCA algorithm. This is described in the SqueezeMeta manual:

> For the amino acid sequence of each gene, DIAMOND (blastp) homology searches are done against the GenBank nr database (updated weekly). A e-value cutoff of 1e-03 is set by default.  The best hit is obtained, and then we select a range of hits (valid hits) having at least 80% of the bitscore of the best hit and differing in less than 10% identity also with the best hit (these values can be set). The LCA of all these hits is obtained, that is, the taxon common to all hits. This LCA can be found at diverse taxonomic ranks (from phylum to species). We allow some flexibility in the definition of LCA: a small number of hits belonging to other taxa than the LCA can be allowed. In this way we deal with putative transfer events, or incorrect annotations in the database. This value is by default 10% of the total number of valid hits, but can be set by the user. Also, the minimum number of hits to the LCA taxa can be set.

and also in the SqueezeMeta paper [here](https://www.frontiersin.org/articles/10.3389/fmicb.2018.03349). I encourage you to read both for finding complete information on how this and other algorithms in SqueezeMeta work.

Best,
Javier
