### ISSUE TITLE
cover.pl function

### ISSUE THREAD

**Issue by fconstancias** [jtamames/SqueezeMeta#193]
Hi again, sorry to open another issue here again ! I am working with a recent SqueezeMeta conda environment and I was intersted in the cover.pl function as described in the manual, but I encontered the following error:

```
(SqueezeMeta201101) $ cover.pl
-bash: /home/constancias/miniconda3/envs/SqueezeMeta201101/bin/cover.pl: Permission denied
(SqueezeMeta201101) $ chmod +x /home/constancias/miniconda3/envs/SqueezeMeta201101/bin/cover.pl
(SqueezeMeta201101) $ cover.pl 
/home/constancias/miniconda3/envs/SqueezeMeta201101/bin/cover.pl: Perl lib version (5.26.2) doesn't match executable '/usr/bin/perl' version (5.26.1) at /home/constancias/miniconda3/envs/SqueezeMeta201101/lib/5.26.2/x86_64-linux-thread-multi/Config.pm line 62.
Compilation failed in require at /home/constancias/miniconda3/envs/SqueezeMeta201101/lib/5.26.2/x86_64-linux-thread-multi/lib.pm line 6.
BEGIN failed--compilation aborted at /home/constancias/miniconda3/envs/SqueezeMeta201101/lib/5.26.2/x86_64-linux-thread-multi/lib.pm line 6.
Compilation failed in require at /home/constancias/miniconda3/envs/SqueezeMeta201101/bin/cover.pl line 8.
BEGIN failed--compilation aborted at /home/constancias/miniconda3/envs/SqueezeMeta201101/bin/cover.pl line 8.
```

Any idea what am I doing wrong here?

**Comment by jtamames** [comment]
Hello

First time I see this one. Apparently it is caused by having mixed versions of Perl, and therefore breaking library compatibility. For instance see [here](https://stackoverflow.com/questions/3883217/why-do-i-get-version-5-12-2-doesnt-match-executable-version-with-perls-par).

If you want to use cover.pl, please download the one in the development branch, since I fixed some issues last week. Also any feedback on this one will be very appreciate, the script is brand new and I would love to know if it is useful.

Best,
Javier

**Comment by jtamames** [comment]
Closed because of inactivity
