### ISSUE TITLE
squeezemeta with RNAseq / metatranscriptomics only

### ISSUE THREAD

**Issue by andreiprodan** [jtamames/SqueezeMeta#206]
Dear developers,

Thanks for an amazing job on a great pipeline! 

I was wondering what the current recommendations are for running SqueezeMeta with metatranscriptomics data only (no shotgun seq available). I've read a (closed) recent similar issue ("Metatranscriptomics" #200), but I'm unsure of the conclusion. 

Should I use rnaSPAdes insted of megahit for the assembly? 

Are there are other adjustments that should be made when the assembly is constructed from RNAseq reads?

**Comment by jtamames** [comment]
Hello!
Thanks for your kind words. We didn't try rnaSPAdes within SqueezeMeta. It should work if you select spades as assembler and pass the --rna flag using -assembly_options in SqueezeMeta (put all options you want between quotes, that is: `-assembly_options "--rna ..."`). You could aldo do the assembly externally and then provide it to SqueezeMeta with the -extassembly option.
The rest of the analysis will be unaffected. Notice that you cannot do the binning with the RNA data, since the coverage of each contig reflects the expression level for the gene(s), thus breaking the assumption that every piece from the same genome must have approximately the same coverage. Run the analysis with the --nobins flag.

Best,
J

**Comment by andreiprodan** [comment]
Choosing spaades as the assembler and using -assembly_options "--rna " causes the pipeline to crash at the assembly stage. I see now that the '' -- meta'' flag is hard-coded in the spades call inside the 01.run_assembly.pl cript. The ''--meta'' is incompatible / mutually exclusive with 'the '--rna'' flag. I've added a few lines of code to my local copy of 01.run_assembly.pl so that it now has a new assembler option 'rnaspades' that uses ''--rna'' instead of ''--meta'' and does not specify any ''-k'' parameters (rnaSPAdes manual strongly advises letting rnaSpades pick the kmer size). The pipeline is running now with ''--nobins'', hopefully it completes successfully. 
Thanks for the quick reply!

Andrei

**Comment by jtamames** [comment]
Great, thank you for let me know! I was not aware of that non-compatibility os rna and meta options. Will take it into account from now on.
Best,
J
