### ISSUE TITLE
TPM values vary when using subsetFun function in SQMtools

### ISSUE THREAD

**Issue by nmquijada** [jtamames/SqueezeMeta#212]
Dear all,

Really nice the SQMTools R package for the analysis and visualization of the data. Great job!

However, I had an issue concerning the TPM values when using the function ```subsetFun```. In order to reproduce the error, I will use the "Hadza" dataset that you include with the package.

So, when looking for a certaing KO (for instance, "K00883", from the "Galactose metabolism" pathway), I got the following TPM values from the entire dataset:
```
Hadza$functions$KEGG$tpm["K00883",]
        H1        H12 
 0.8208981 63.9219134
```
This value is the same that would be found in "Project-in-SQM/results/tables/VB2.KO.tpm.tsv". However, when I use the ```subsetFun``` function (disabling the recalculation of TPM), either for the pathway or the specific KO, the TPM values change respect with the ones above:
```
met= subsetFun(Hadza, fun = "Galactose metabolism", rescale_tpm = F, rescale_copy_number = F)
met$functions$KEGG$tpm["K00883",]
    H1    H12 
 0.161 13.599 

metKO=subsetFun(Hadza, fun = "K00883", rescale_tpm = F, rescale_copy_number = F)
metKO$functions$KEGG$tpm
          H1    H12
K00883 0.161 13.599
```

Is this expected to happen? Am I missing any parameter that should be parsed to ```subsetFun```?

I was using SqueezeMeta v1.1.1 and SQMtools v0.4.5 but also tried with SQMtools v0.6.0 by following this instructions https://github.com/jtamames/SqueezeMeta/issues/150#issuecomment-688129521 

Thank you very much for your time,
Narciso

**Comment by fpusan** [comment]
Can reproduce.
For now, you can use copy numbers instead, which are not suffering from this issue.

**Comment by nmquijada** [comment]
Thanks for the quick answer!
As part of my dataset is from metatranscriptomic data, would you recommend using copy number? I don't know if the reference genes can undergo differential expression profiles that might alter their "constant" number.

**Comment by fpusan** [comment]
Depends on who you ask. In https://www.sciencedirect.com/science/article/pii/S009286741931164X they use a set of reference single copy genes which they claim are also housekeeping genes and thus can be used for both metagenomics and metatranscriptomics.
We actually include those in the latest version of SQMtools (see `?MGKOs` or `?MGOGs`) although we do not use them by default. However, instructions on how to use them to normalize the data can be found under `?USiCGs`.

**Comment by nmquijada** [comment]
Awesome! Thanks a lot for the answer.

**Comment by fpusan** [comment]
Finally got some time to look into it. The problem is that, from version 1.3 onwards, unmapped reads are taken into account when calculating TPMs when creating the tables initially, but not anymore when subsetting the data. Thus the original TPMs are much lower than the TPMs in the subsetted dataset.

We'll look to fix this for version 1.3.1 (coming hopefully soon)

**Comment by nmquijada** [comment]
OK! Thank you very much for looking into it.
Looking forward to the next release!
Best,
Narciso

**Comment by fpusan** [comment]
Hopefully fixed in #6fd5729. Here's your example after the latest develop patch (the exact TPM numbers are not the same since I have updated the example dataset).

```
library(SQMtools)
met     = subsetFun(Hadza, fun = 'Galactose metabolism', rescale_tpm = F, rescale_copy_number = F)
metKO =subsetFun(Hadza, fun = 'K00883', rescale_tpm = F, rescale_copy_number = F)

Hadza$functions$KEGG$tpm['K00883',]
#      H1      H12 
# 0.73923 86.94740 
met  $functions$KEGG$tpm['K00883',]
#      H1      H12 
# 0.73923 86.94740 
metKO$functions$KEGG$tpm['K00883',]
#      H1      H12 
# 0.73923 86.94740 
```
There will be still minor differences between the TPM of the object you get after loading the project with `loadSQM` and its subsets. This is related to some approximations we make when calculating the TPMs of subsets in order to speed up things. The differences should however be small and not affect the interpretation of the results.

**Comment by nmquijada** [comment]
That is great. Thank you very much for taking care of this issue. I will update to this patch.

Before closing this issue, I would like to ask you something:

How do you deal with the TPM/abundance values of those genes that belong to more than one metabolic pathway when you want to compare the expression/abundance of two (or more) pathways?

For instance, *fadJ* (K01782). According to keggfun2.txt:

```
K01782	fadJ	3-hydroxyacyl-CoA dehydrogenase / enoyl-CoA hydratase / 3-hydroxybutyryl-CoA epimerase [EC:1.1.1.35 4.2.1.17 5.1.2.3]	Metabolism; Carbohydrate metabolism; Propanoate metabolism | Metabolism; Carbohydrate metabolism; Butanoate metabolism | Metabolism; Lipid metabolism; Fatty acid degradation | Metabolism; Amino acid metabolism; Valine, leucine and isoleucine degradation | Metabolism; Amino acid metabolism; Lysine degradation | Metabolism; Amino acid metabolism; Tryptophan metabolism | Metabolism; Metabolism of other amino acids; beta-Alanine metabolism | Metabolism; Metabolism of terpenoids and polyketides; Limonene and pinene degradation | Metabolism; Metabolism of terpenoids and polyketides; Geraniol degradation | Metabolism; Xenobiotics biodegradation and metabolism; Benzoate degradation | Metabolism; Xenobiotics biodegradation and metabolism; Caprolactam degradation
```

If you would like to compare "Propanoate metabolism" and "Butanoate metabolism" expression, for instance, and you subset the dataset for those pathways, *fadJ* will appear for both subsets with the same TPM/count values.
I know it is hard to predict in which pathway the enzime is actually working (maybe you can look on the expression values of the  genes that are close to *fadJ* in a specific metabolic pathway, and infer that is "more active" in that pathway where the close genes are more expressed in comparison with the other pathway?). Is there any normalization that must be applied in order to preserve the final TPM/count values? (such as dividing the TPM/count value by the number of pathways in wich each gene is involved in?)

Thank you very much for your time

**Comment by fpusan** [comment]
> Is there any normalization that must be applied in order to preserve the final TPM/count values? (such as dividing the TPM/count value by the number of pathways in wich each gene is involved in?)

This would at least preserve the total TPM/count/copy_number values, which in my opinion beats just counting the same enzyme twice if it appears in two pathways.

However, I'd say that blindly computing "pathway" abundances is generally not a very good idea, for several reasons. The ones below are the ones that come right to my mind.
1) As you say, some enzymes appear in several pathways, so it's hard to know what pathway the enzyme really contributing to in your sample.
2) Incomplete pathways will have an abundance, as long as some of the enzymes are present (maybe because they also appear into another pathway). If you are not careful you will end up analyzing and discussing pathways that are not really there.
3) In particular, KEGG pathways group together functions that are physiologically unrelated (e.g. "sulfur metabolism" will group together assimilatory sulfur acquisition, sulfate oxidation and sulfate respiration). It is fine to have them together in the same map and look at them, but I would not add their abundances and treat them as if they were a single feature. MetaCyc pathways are much more granular in this regard. Even in their case, defining whether a pathway is present or not without manual curation requires a complex set of rules (e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3368424/) which in my experience are often far from perfect.

I personally would use KEGG pathways as a tool for representing the data visually, but I would not compute pathway abundance measurements, and as a reviewer I would certainly not trust any evidence based on that metric alone.

I generally focus initially on KEGGs/COG/PFAM profiles. If I want to discuss a particular pathway (because some enzymes belonging to that pathway have an interesting distribution, or because my prior knowledge about the ecosystem indicates that the pathway might be interestingly) I would definitely do that manually, looking at the literature, trying to solve inconsistencies / missing reactions, etc.

**Comment by nmquijada** [comment]
Thanks a lot for the nice discussion and your suggestions. They were really helpful. I definitely agree with the biases you stated.
Indeed, KEGG pathways represent a nice way to visualize the data, but I would go for some "manual pruning" when looking for a particular function.
All the best.
