### ISSUE TITLE
seqmerge crashes

### ISSUE THREAD

**Issue by andreiprodan** [jtamames/SqueezeMeta#219]
Hi! I've been trying to find the best approach for a large dataset (100+ fecal microbiome samples of > 10 mil reads each). Seqmerge sounds like a great idea, but keeps crashing, have not been able to successfully run seqmerge mode on any datasets (though merged mode works fine). 

Tried seqmerge on the Hadza test dataset as well as on a small dataset I made myself, same result:

Error running command:   ...envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/kmerdist.pl ....squeezemeta/db/test/Hadza 1 >> ...squeezemeta/db/test/Hadza/syslog 2>&1 at ...envs/SqueezeMeta/SqueezeMeta/scripts/01.merge_sequential.pl line 56.

(I removed some of the path for brevity)

I saw that the line 56 error in kmerdist.pl has come up before in issues, but the solution presented there (adding ' -k 12' to line 61 of kmerdist.pl) is already implemented in this version of SqueezeMeta and does not seem to solve the problem.

Any ideas on what's going on? Thanks!

**Comment by andreiprodan** [comment]
I'm attachinng the syslog and progress files


[progress.log](https://github.com/jtamames/SqueezeMeta/files/5753484/progress.log)

[syslog.log](https://github.com/jtamames/SqueezeMeta/files/5753479/syslog.log)

**Comment by fpusan** [comment]
The problem lies here.
`Cwd.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xcd00080)`
It seems that your system has multiple versions of the perl interpreter and/or the libraries, and that there is a mismatch.

Please edit ` ...envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/kmerdist.pl ` and change the first line to

`#!/usr/bin/env perl`

This should force the program to use the perl interpreter bundled with conda (which we already do for the rest of the scripts, but we missed this one apparently). I think this should do the trick, let me know if it works.

**Comment by andreiprodan** [comment]
That indeed solved the error! Thanks, and a happy new year!

**Comment by fpusan** [comment]
Glad to hear! Fixed in 5e06d45, gig closed
