### ISSUE TITLE
Question on gene annotation when using an external database

### ISSUE THREAD

**Issue by eperezv** [jtamames/SqueezeMeta#223]
Hello,
I was checking the gene annotation produced by SqueezeMeta and I found something weird. I do not know if I am missing something or there is something wrong.

I run SqueezeMeta with an external database. After checking the file 04. regarding my database, I found one of my genes of interest was identified with 100 % of identity, and e-value of 2.1e-217. After checking the orf table (13.), I saw that this region was assigned to a different gene.

I am guessing SqueezeMeta is then finally annotating the gene based on the results from other databases (e.g. KEGG, which is missannotated for that gene). Could it be possible? In any case, I've checked the blast outputs (all files 04) and the hit from my database seems the one with the lowest e-value (similar identity and length in all cases). 
Thank you

**Comment by jtamames** [comment]
Hello!
SqueezeMeta does not select any functional annotation, because we think the user must decide which one is to be used. We provide all annotations. Therefore, table 13 should include annotations from all databases, including the external one you used. Could you please paste the table's headers and the full line for the target ORF?
Also, there should be a 07 file in the results directory corresponding to your external database. Could you check if it is there, and check the result for the target ORF?

Best,
J

**Comment by eperezv** [comment]
Ok. After a better looking at table 13, I understand. It makes total sense. File 07 is also right.
Thanks for your help
