### ISSUE TITLE
Create my own database for taxonomy 

### ISSUE THREAD

**Issue by kassammohamed** [jtamames/SqueezeMeta#231]
Hello,

I would like to know if there is a possibility to use personal database for the taxonomy assignment instead of ncbi nr?

**Comment by jtamames** [comment]
Hello
So far this feature is not implemented, and we don´t plan to do it in the near future. The nr is not useful for your purposes?
Best,
Javier

**Comment by kassammohamed** [comment]
Hello,
Actually sometimes we create our own db filtered depening to questions. Additionally we have internal genomes that are not published that we would like to include as reference.
Maybe if you can explain me where i can add before making the db i can do it manually.

**Comment by jtamames** [comment]
Hello
It is not straightforward because the taxonomic database is stored in a sqlite db that needs much more processing than the functional ones, which we simply format for diamond.

At the end, what we do is processing the GenBank file that we download from NCBI, containing the full nr database. If you manage to put your sequences in fasta format, including a valid taxonomy (meaning one that is compliant with the [NCBI's taxonomy database](https://www.ncbi.nlm.nih.gov/taxonomy), you could more or less easily create a new database including the sqlite structure. The entries should look like this:

 >YP_009518751.1 DNA polymerase III subunit gamma [Escherichia coli str. K-12 substr. MG1655]
MSYQVLARKWRPQTFADVVGQEHVLTALANGLSLGRIHHAYLFSGTRGVGKTSIARLLAKGLNCETGITA
TPCGVCDNCREIEQGRFVDLIEIDAASRTKVEDTRDLLDNVQYAPARGRFKVYLIDEVHMLSRHSFNALL
KTLEEPPEHVKFLLATTDPQKLPVTILSRCLQFHLKALDVEQIRHQLEHILNEEHIAHEPRALQLLARAA
EGSLRDALSLTDQAIASGDGQVSTQAVSAMLGTLDDDQALSLVEAMVEANGERVMALINEAAARGIEWEA

The taxonomy must go in the sequence header, between brackets. Remember also that the sequences must be aminoacid ones.

Then, edit the `lib/install_utils/make_nr_db_2020.pl`, commenting lines 27-31, reading:

> my $command="wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz -nc -P $databasedir";
> system $command;
>#-- Format the database
>system("gunzip $databasedir/nr.gz && mv $databasedir/nr $fastadb");

Then provide your fasta file as a file named nr.faa in the database directory ($databasedir in SqueezeMeta_conf.pl), and run `utils/install_utils/make_databases.pl`. I hope it works.

Best,
Javier

**Comment by kassammohamed** [comment]
Hello Javier

Thank you very much for the explanation. I will sure try and update you if that works.

Quick question regarding the taxonomy tree file. Do i need to update the tax file too or not ?

**Comment by jtamames** [comment]
Hello

No you don´t, that is taken directly from taxonomy. Just make sure that you use correct names for the taxa.

Best,

**Comment by kassammohamed** [comment]
Hello Javier,

Thank you very much it works perfectly.
