### ISSUE TITLE
How to minimize the computational time?

### ISSUE THREAD

**Issue by lnjusto** [jtamames/SqueezeMeta#232]
Hello! Thank you for your outstanding work, SqueezeMeta seems to be the future of metagenomic analyses.

My main issue is how could I shorten the analysis time?

I'm running the full automatic pipeline (coassembly mode) using 16 samples (total size of around 200 GB) in a cluster's node with 40 GB of RAM available. It is running for a month right now, on the MaxBin step at this exact moment. Should the analysis take this long?

By the way, this is just a test run. I pretend to use a bigger dataset, but I'm quite afraid of the computational time. If I've understood correctly, I could separate my dataset in half and run parallel assemblies (using script 01) in different machines, and then merge the resulting contigs by the user-supplied assembly function. In this way, I could try to minimize the assembly time, correct?

Alternatively, is there a way that I could try to merge projects or projects' results? In SQM tools using R maybe? I'm just trying to figure out ways that I can parallelize de processes.

Thank you in advance!

**Comment by fpusan** [comment]
Maxbin can be slow to run, yeah. How many threads are you using?

Do you really need binning results? There is a flag to skip those steps if you don't. You can also skip only maxbin, and keep the results from metabat (which runs faster). I think other users have managed to include concoct results into SqueezeMeta, this is not supported oficially yet but will come eventually.

Yes, you can combine results from different projects, but it is currently limited to taxonomic and functional profiles. We currently don't support combining bins generated in different projects (although we have run some tests internally).

**Comment by jtamames** [comment]
Hello, and thanks for your kind words!
Analysis time is highly dependent of several factors, but one month for your test run seems excesive, very much so. In our experience, users reporting slowness often are facing some kind of disk I/O problems, so even you have enough CPU and RAM still the process is running very slow. See for instance  #216. Check if that is the case.

Besides, the MaxBin step is very slow, just because MaxBin is very slow itself. You could select to skip it using the flag --nomaxbin when running the pipeline, but that will make to build bins just relying on Metabat. It depends on how much you are interested in the bins. In a hopefully incoming version 1.4.0 we will introduce custom binning selection that will make it easy to select binning methods and use different ones. Take a look also to #69

And in reference to merged assemblies, it doesn´t work exactly like that, but you could manage to do more or less what you want. You could run individual assemblies in sequential mode, then create an empty project in merged mode, copy the individual assemblies there, run the 01.merge_assemblies.pl script, and once you have the merged assembly, restart in step 2. But take into account that the merge will take long (minimus2 is also rather slow).

Best,
Javier

**Comment by lnjusto** [comment]
Thank you so much for your quick response! 

Perhaps I wasn't very clear about MaxBin. I'm not worried about it, specifically. It is taking some time, yeah, but not a big deal for now. I was just giving a reference point of the step that I'm in on the pipeline. I think MaxBin is functioning normally, but should I be in this step after one month of analysis using 16 samples, 40 RAM, and the default number of threads? 

I guess I'm really in an I/O bottleneck. iostat results bellow:

Linux 3.2.0-23-generic (amazonia01) 	01/25/21 	x86_64	(40 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
                 31.83     0.00    1.47          0.37     0.00      66.33

Device:          tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda               0.23         0.58         2.37       2904551    11941440

I'm now contacting server support to confirm these values, but it seems that the I/O speed too slow. If these values are right I will try to change the disk for a faster one. Could you tell me which steps are more I/O demanding? 

As I'm using a server with a variety of clusters, I guess the most clever way to use SqueezeMeta is to run scripts individually on the cluster that best suits the demands of a specific step (running the assembly on the cluster with the most amount of RAM, for example). In this case, I would have to study the computational demands of each step. Could any of you enlighten me with this knowledge or some references? 

Best wishes!

**Comment by lnjusto** [comment]
Thank you so much for your responses, I think they were quite useful!

I think I have understood the computational demands of each step. 

As I said, I'm running SqueezeMeta in a cluster. However, in my test analysis, I have only used one powerful node of the cluster (one with tons of RAM). I'm curious regarding parallelization and the number of threads in SqueezeMeta. Does any step have the potential to be parallelized in a series of nodes in a cluster? In your experience, increasing or decreasing the number of threads have made any substantial difference in the computational time?

**Comment by jtamames** [comment]
Hello!
Most steps could be parallelized since they can be divided into independent blocks of data. Indeed it is what we are doing in steps 06 (tax assignment) and 10 (counting abundances), splitting the data in `$numthreads` and opening that number of threads. I guess you can do that in a cluster if you can set up the procedure for gathering and merging results form each node. 

We haven't make a careful benchmarking of computing times regarding threads, so I cannot answer the second question.

Best,
Javier

**Comment by lnjusto** [comment]
Hello Javier! 

Interesting... Could I parallelize steps 1, 4, and 5? Those are the ones that took more time in my test analysis (9, 9, and 5 days respectively)  How could I divide my data into data blocks? Could I run a series of sequential mode analyses in a group of nodes in a cluster and then merge all of them using combine-sqm-tables.py? Do you have any suggestions of how could I do that? I guess it could significantly minimize the computational time.

No worries about the threads benchmarks ;)

Best wishes

**Comment by lnjusto** [comment]
For instance,

Is it possible to run several independent projects in sequential mode (with only one or two samples in each one) and then merge the projects' results using combine-sqm-tables.py? If so, I could run each independent project in a cluster's node and then merge all projects' results in a single table that I could analyze using R (one SQM project with all my results).

**Comment by jtamames** [comment]
Hello
Yes, but using combineSQMlite instead of combineSQM. The second needs the same structure of genes and contigs in all projects to create combined tables. The first merges and rescales the counts for taxa and functions., and therefore it is gene/contig  independent. The cost is that with combineSQMlite you lose the subset functionality.
Best,
Javier

**Comment by lnjusto** [comment]
Hello,

Thanks for your answer!

I'm particularly interested in using the subset functionality, so I don't think using SQMlite is a good idea in my specific case.

What do you mean by "needs the same structure of genes and contigs in all projects to create combined tables" exactly? Is there a way that I could structure the projects/projects' results in order to use combineSQM instead? Perhaps if each project only has one sample? Avoiding creating an artifact of course.

**Comment by fpusan** [comment]
Hi!
Just a quick heads up, you can use the subset functionality as long as you do it on "proper" SQM objects (so not SQMlite objects).
So if you have different projects (e.g. because you did a sequential run) you can subset each one of them (since they are "proper" SQM objects) and them run `combineSQMlite` over all the subsets. This will yield a `SQMlite` object (so you can't subset it anymore) but at this point you don't care since you did the subsetting before combining.

**Comment by jtamames** [comment]
Closing issue, feel free to reopen
