### ISSUE TITLE
taxonomy unmapped

### ISSUE THREAD

**Issue by RaulLanda** [jtamames/SqueezeMeta#254]
Hello!
I have a doubt about the "unmapped" classification in taxonomy assignation.  I used SqueezeMeta in the v1.0 versión, and only could get the SQMlite object for R analysis. Decided to run it again with the v.1.3.1 version to get the SQM object (wanted to do some prunes)  and  now I'm getting an Unmapped classification (almost 50% of each sample) besides the unclassified. 

Do I have to worry?

**Comment by fpusan** [comment]
Hi!

You can check whether the result is correct by looking at the file in `/path/to/your/project/results(10.*.mappingstat`. The file contains the mapping percentages for each sample, they should match with what you are seeing in SQMtools.

50% unmapped reads is not great, it means that your assembly is incomplete. That can happen if your community is too comples or if you have too few reads. In our experience it also happens more frequently with transcriptomic data, although we are not sure of the reason yet.

What kind of analysis are you running (molecule type / samples / assembly mode etc)

**Comment by RaulLanda** [comment]
I ran a coassembly mode using an external assembly (used the same for the v1.0 and v1.3.1)

**Comment by jtamames** [comment]
Hello
What can you see in the 10.*.mappingstat file?
Best,

**Comment by RaulLanda** [comment]
Wed Feb 24 12:21:28 2021
# Sample    Total reads     Mapped reads     Mapping perc       Total bases
Muestra1     156624866     60853892          38.85                    23493729900
Muestra2     159425578    78958068           49.53                   23913836700
Muestra3      135722398    79640716          58.68                   20358359700

# Notice that mapping percentage is low (<50%) for some samples. This is a potential p
roblem,  meaning that most reads are not represented in the assembly
# Notice also that you set the minimum contig length to 500. In this way you are remov
ing the contigs shorter than that size. This can be, at least partially, the cause of
this low mapping percentage
# It is likely that redoing the analysis with the default minimum contig length (200)
can solve this problem
# If not, you could redo your analysis using assignment of the raw reads instead of re
lying on the assembly. Use sqm_reads.pl or sqm_longreads.pl for this purpose. That str
ategy will not provide bins

**Comment by jtamames** [comment]
Yep. So the thing is that your sequences assembled poorly. What are you studying, soils perphaps?
You can try with a different assembler, although in my experience that doesn´t improve dramatically the results. You can also proceed with your analysys (it is not that terrible, but you must take into account that you are missing part of the diversity in your samples), or you can choose to analyze the raw reads instead, not relying on the assembly. It is possible also to use the--singletons option in SqueezeMeta, that introduces the unmapped reads as if they were contigs. But I will not reccomend it to you for your samples, because it will introduce like 240M new contigs and that will drive you crazy. And we don´t want that :)
Best,
J

**Comment by jtamames** [comment]
Closing issue, feel free to reopen
