### ISSUE TITLE
Using lca.pl standalone?

### ISSUE THREAD

**Issue by Jigyasa3** [jtamames/SqueezeMeta#257]
Hey all!

I am not a bioinformatician, but I already have diamond blastp results of proteins in metagenome contigs and not much space on the Linux machine to install the software. I was wondering if it's possible to use the `lca.pl` and `summarycontigs3.pl` directly on the diamond output?
I have the taxonomy mapping file too. 

Looking forward to your reply!

**Comment by jtamames** [comment]
Hello!
I am afraid it is not possible without installing the software and the databases, because SqueezeMeta uses a sqlite database for querying the taxonomy of each hit. We could send you the pre-formatted sqlite database, but it still amounts to 50 Gb at least. If that is possible for you, we could try.

Metagenomics, by definition, is bulky. Couldn´t you get some extra space to keep the data?
Best,
J

**Comment by Jigyasa3** [comment]
Hey @jtamames 

Thank you for replying! I can make space for 50Gb. Thank you so much for the suggestion! Would that mean that I would run the analysis from assembly step (step1) or taxonomy annotation (step4) based on the manual? I already have trimmed raw reads and assembled contigs.

**Comment by jtamames** [comment]
Hello
That unfortunately won´t be enough. The database itself amounts a bit more than 50 Gb, and then you will need some extra space for the results. No way to get more disk space?

**Comment by Jigyasa3** [comment]
I can get max 200Gb (pushing it), would that be enough?
