### ISSUE TITLE
 forward and reverse merged

### ISSUE THREAD

**Issue by mariemh23** [jtamames/SqueezeMeta#260]
Hi!

I would like to know if it is possible to use Squeezemeta on merged sequences (reverse and forward paired sequences) ?  if so, how can I specify it in the "sample" file ?

Thanks

**Comment by mariemh23** [comment]
Hi !
I have shotgun sequences (not amplicons)
I want to merge them before assembling step. I already tried this approach but I noticed that specifying the location of the files in the sample file is not enough, you also have to mention it in the command line (with  -extassembly option), otherwise SqueezeMeta starts the assembly step. As I have about thirty samples, I did not know how to indicate the link of the assembly file each time in the command line.
Best

**Comment by jtamames** [comment]
So, if I understand it correctly, you have 30 (around) samples, each with its corresponding external assembly? In the current v1.3.1, you can specify the external assembly for each sample in the samples file, please refer to page 9 of the manual for the explanation.

Best,
Javier

**Comment by fpusan** [comment]
Hi @mariemh23 . The `extassembly` option is used when you already have an assembly, and you only want to annotate it and map the reads against it. If I understand you correctly what you want is not this, but to first merge the paired end reads into larger sequences AND THEN assemble those larger sequences with SqueezeMeta.

If that's the case, you should merge the fwd and rev reads before running SqueezeMeta. This will give you one file per sample, which you can include in the samples file instead of the usual two files per sample (so for each sample you would only have one line ending in "pair1").

Is this what you wanted to do? If so, may I ask why? We would rather recommend to input the forward and reverse reads separately, and let the assembler take care of the rest.

**Comment by mariemh23** [comment]
Hi @fpusan !!

yes, that was what I wanted to do, but I think I will follow your suggestions. 
One last thing, I also have a suggestion. You should include a tool to remove contaminated sequences (vectors, human sequences) in addition to Trimmomtatic. This is really common, especially for certain types of samples, like mine which are from newborn stools

Thank you both @fpusan @jtamames  so much for your help.

Best regards

**Comment by jtamames** [comment]
Hello @mariemh23 

Thanks for the suggestion, we will look into it!

Best,
Javier
