### ISSUE TITLE
External coassembly and external bins

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#263]
Hi,

I have a coassembly and metabat2, maxbin2, and concoct bins generated using [MetaWrap](https://github.com/bxlab/metaWRAP), and I was wondering whether I can run SqueezeMeta on this assembly using the -extassembly and --nobins flags?

Also, after SQM has finished, would it be possible to copy the external bin sets I have to the appropriate location (where normally bin sets generated by SQM would be stored) and restart SQM from step 16 onwards (including DAS tool)?

Would such a procedure work or are assemblies/bin sets generated by MetaWrap not directly compatible? Or am I missing any other details to make this work?

Best,
Sam

**Comment by jtamames** [comment]
Hello!

>  I have a coassembly and metabat2, maxbin2, and concoct bins generated using MetaWrap, and I was wondering whether I can run SqueezeMeta on this assembly using the -extassembly and --nobins flags?

Yes, no problem, start the run and provide the contigs resulting from binning as external assembly. You could also add `-test 13` in the command line for the run to stop after step 13 and no proceeding with binning. Then add your bins manually (see next point). In this case I would not set `--nobins` because that will skip everything related with bins (DAS Tool, checkM, bin table...), and you still want that.

> Also, after SQM has finished, would it be possible to copy the external bin sets I have to the appropriate location (where normally bin sets generated by SQM would be stored) and restart SQM from step 16 onwards (including DAS tool)?

Yes. The binning directories can be set in the `SqueezeMeta_conf.pl` file in the project directory. There a hash `%bindirs` is defined, with the location of all binning results. You can add or skip as many as you want. So you could add a "metawrap" directory containing the metawrap bins, for instance. Then restart in 16 for DasTool.

> Would such a procedure work or are assemblies/bin sets generated by MetaWrap not directly compatible? Or am I missing any other details to make this work?

As long as they are fasta files, SqueezeMeta will not care. Rather promiscuous :)

Best,
Javier
