### ISSUE TITLE
Post-run cleanup of files?

### ISSUE THREAD

**Issue by gruningerrj** [jtamames/SqueezeMeta#275]
I couldn't find this topic in any of the previous issues so hopefully this is not a redundant question. I would like to cleanup my sqm directories after a run to reduce storage space on our server. Is it possible to remove some of the directories that are not required for downstream analysis? if so what can be removed and what cannot be removed? The largest directory seems to be data/sam but I am not sure if these are required for downstream analysis. 

Thanks

**Comment by fpusan** [comment]
Depending on what downstream analysis you need. The SAM data can be removed as long as you don't plan on generating anvi'o databases.

**Comment by gruningerrj** [comment]
I would like to use anvi'o. Can these be converted to BAM format? I'm not sure how much space that would free up. What about the megahit files? if all that is needed is the final contigs fasta file there could the intermediate files be removed?

**Comment by fpusan** [comment]
Hi!
If you want to use anvi'o I would first run `anvi-load-sqm.py`, which will convert the SAM files into BAM files, and then load them into an anvi'o database. At that point I'm pretty sure that the SAM files and the BAM files can be removed. Maybe @ggnatalia can give you more details on what files you need to keep in order to be able to use anvi'o.
Regarding the `intermediate` directory, I'm pretty sure that only the `09.*` and `19.*.contigsinbins` files are needed by SQMtools. I would make a backup just in case, then remove everything but those files from the `intermediate` directory, and finally try running `sqm2tables.py` + SQMtools. If it works then you should be good to go.
Let me know if that works!
Fernando
