### ISSUE TITLE
Stopping at STEP18

### ISSUE THREAD

**Issue by mdjlynch** [jtamames/SqueezeMeta#28]
Useful pipeline. Seems to be crashing at line 136 of the checkM script and it appears to be an issue with the CheckM markers (nothing in the checkm_markers folder).

```
Bin 1/77: maxbin.077.fasta.contigs.fa.tax
 Using profile for order rank : Clostridiales
Error running command:    export PATH="/home/mdjlynch/bioinformatics-tools/SqueezeMeta/scripts/../bin/pplacer":$PATH; /home/mdjlynch/bioinformatics-tools/SqueezeMeta/scripts/../bin/checkm taxon_set order Clostridiales /home/mdjlynch/working/pilot-1-to-6-ensemble-binning/data/checkm_markers/Clostridiales.ms > /dev/null 2>&1 at /home/mdjlynch/bioinformatics-tools/SqueezeMeta/scripts/../scripts/18.checkM_batch.pl line 136.
Stopping in STEP18 -> 18.checkM_batch.pl
```

Thoughts?

Thanks.

**Comment by fpusan** [comment]
Hi!

Did it work with the test dataset?

What is the output when you run

`export PATH="/home/mdjlynch/bioinformatics-tools/SqueezeMeta/scripts/../bin/pplacer":$PATH; /home/mdjlynch/bioinformatics-tools/SqueezeMeta/scripts/../bin/checkm taxon_set order Clostridiales /home/mdjlynch/working/pilot-1-to-6-ensemble-binning/data/checkm_markers/Clostridiales.ms `

?

**Comment by mdjlynch** [comment]
Looks like it failed in the same spot for the test data.
```

Traceback (most recent call last):
  File "/home/mdjlynch/bioinformatics-tools/SqueezeMeta/scripts/../bin/checkm", line 45, in <module>
    from checkm import main
  File "/home/mdjlynch/bioinformatics-tools/SqueezeMeta/bin/../lib/checkm/main.py", line 28, in <module>
    from checkm.resultsParser import ResultsParser
  File "/home/mdjlynch/bioinformatics-tools/SqueezeMeta/bin/../lib/checkm/resultsParser.py", line 34, in <module>
    from checkm.coverage import Coverage
  File "/home/mdjlynch/bioinformatics-tools/SqueezeMeta/bin/../lib/checkm/coverage.py", line 30, in <module>
    import pysam
ImportError: No module named pysam

```

I can import pysam from the python interpreter directly.

**Comment by fpusan** [comment]
It's likely that your python interpreter is not in a standard location (at least not in the location checkm expects it to be!).

checkm expects python2 to be located in `/usr/bin/python`. You do have an interpreter in that location, but it lacks the required modules. Possibly your default interpreter (with the right modules) is located elsewhere.

What path do you get when typing `which python`?

Also when you run `python` do you get a python2 interpreter, or a python3 interpreter?

If it's a python2 interpreter, just modify the first line of the checkm script (in `/home/mdjlynch/bioinformatics-tools/SqueezeMeta/bin/checkm`) so that it points to your default interpreter (the one you get when typing `which python`.

Else, install the required dependencies for `/usr/bin/python`. You can do it by typing `/usr/bin/python -m pip install MYMODULE`.

Let me know if this works for you.

**Comment by mdjlynch** [comment]
Yes, that's it. I created a conda environment for SqueezeMeta and defaulted to python2. Changed the script to python2 and installed the dependencies. Seems to be working.

Thanks.
