### ISSUE TITLE
Ensure high mapping quality for external database

### ISSUE THREAD

**Issue by haegih** [jtamames/SqueezeMeta#282]
Dear SqueexeMeta team,

I ran the pipeline with the --extdb option to include the CARD database as well. Everything went smoothly, however I am now wondering if there is a way to ensure that only high quality CARD mappings are included in terms of sequence identity, bitscore, etc.?

Thanks,
Hannah

**Comment by jtamames** [comment]
Hello Hannah

I do not know CARD in detail, but I understand by your words that it has a "high quality" section or tag identifying curated entries, is that so? It is not possible to identify these properly because there are no metadata attached to the database entries. What you could do is to create a new external database composed of high quality CARD entries, and run SqueezeMeta using BOTH. In that case you could have, in different columns, all CARD annotations and high quality ones. Then it would be easy to select one set or the other, either parsing the tables or using SQMtools for that purpose.
Best,
Javier

**Comment by haegih** [comment]
Hi Javier, 

Thanks for your fast response! 

However, it seems that my question was ambiguous, sorry for that. 
What I actually meant is that I am wondering if there is a file generated by SqueezeMeta which includes information about the sequence identity between my sequences and the genes of the external DB, such that I can filter out the genes that have an identity below e.g. 70%.
I know that there is a parameter `-miniden` that makes sure that the minimum identity is e.g. 60%, but does this only apply for KEGG, COG and Pfam or is this also guaranteed for the functional annotation when including an external database?

Thanks a lot!
Hannah

**Comment by jtamames** [comment]
Hello Hannah!
Sorry for the misunderstanding. In addition to mioniden, you can change the values in the parameters.pl file that is created in each SqueezeMeta run. That controls the settings for the different taxonomic and functional annotations. You can change, for instance, $minidenfun4 that controls the minimum identity for functional assignment.
We don't keep the identity values for the annotations (maybe we should). The only way is to set up different identity values and redo the step 7 for functional annotation. 
Best,
Javier

**Comment by haegih** [comment]
Hi Javier, 

great, then I will change the parameters then, thanks a lot! 

Have a great weekend,
Hannah
