### ISSUE TITLE
Expected run time for merging assemblies

### ISSUE THREAD

**Issue by mradz19** [jtamames/SqueezeMeta#291]
Is there any way to estimate run time for merging assemblies?

I started a run on the 15th of April (merged) and on the 18th it started merging the assemblies with minimus2. It still says it is merging and only the 99.delta file is being continuously updated, no other file has been updated since the 18th. Is it possibly stuck? I'm running with 16 threads and checking on htop nucmer is currently running

**Comment by jtamames** [comment]
Hello
If you see it running then it is not stuck, but minimus2 is very very slow on big assemblies like yours. We are looking for a solution, but currently we must be patient with that. I don´t know any way to estimate the remaining time. Sorry about all that.
Best,
Javier

**Comment by jtamames** [comment]
Hello again

Just thinking... The problem with minimus2 is that it calculates overlaps between contigs and scales badly. Obviously the algorithm can be vastly improved, but until we find a better solution, something that can help will be to reduce the number of contigs in the individual assemblies. Then it would be advisable to use the -c parameter when running the project. This will set the minimum contig length to the size you want. I would try with -c 1000. That will decrease very much the number of contigs and speed up the whole process.

The drawback is, of course, that you will lose contigs. But perhaps not that much sequence, since these will be small and low-coverage ones. You can try doing the merge with -c 1000 and then taking a look at the mappingstat file, to see the mapping percentage there. Then you can decide if the loss is manageable or not.

Best,
Javier

**Comment by mradz19** [comment]
Thanks for the info. Just confirming should I expect any other file to be updating or only the 99.delta one?

**Comment by jtamames** [comment]
That is created by nucmer, that it is the process taking so long. Not sure if it is creating additional files.
