### ISSUE TITLE
Explanation of Congruent bins?

### ISSUE THREAD

**Issue by gruningerrj** [jtamames/SqueezeMeta#292]
Hi again,

After a long time my dataset finally made it through the pipeline and I am starting to explore the results. For people's reference, I had large novaseq read files from 16 samples and it took 40 days to run through the pipeline. ~24 days to get through maxbin2, 2 days for metabat2. In the end there were 916 bins (about what I would expect from this environment), 296 of these were good or high quality. Interestingly, 218 of the good quality bins were from metabat2, 78 from maxbin2.  There is  line in the summary results that indicates there are 320 'congruent bins' but I have not been able to figure out what exactly that means. Can someone explain what a congruent bin is, or share a reference that could explain this?

Thanks,
Rob

**Comment by jtamames** [comment]
Hello Rob
Oh well, good example of patience! Maxbin is way too slow, we are sorry for that.
Regarding your question, a congruent bin is one in which all contigs are in agreement with the consensus taxa. Remember that we assign a taxon for each contig, and then we derive the taxon for the bin as the consensus of the contigs' taxa. That means that there are no contigs with conficting taxoomic annotation. It can be seen like another measure of the "purity" of the bin, different from contamination.

Best,
Javier

**Comment by gruningerrj** [comment]
Perfect! That makes sense

Thanks

**Comment by gruningerrj** [comment]
After digging a bit more to see how this could be used to help identify potentially problematic bins I could find where the congruency is listed in the output but I found noticed the post about disparity values. Is this congruency captured in the disparity value? Do you have any advice on a reasonable cut-off value for disparity index to flag bins that need closer inspection?

**Comment by jtamames** [comment]
Hello again
Now that you say it, perphaps we are not being too "congruent" in our definitions on this issue. Let me expalin them:

For a particular contig, disparity measures how many genes disagree with the consensus taxonomic annotation of the contig. This is intended to spot chimeric contigs. But sometimes a misassembled contig will not have a consensus taxon, precisely because it is a chimera. Therefore, to spot potential assembly problems, look for contigs with high disparity or with no consensus taxon.

For bins there is also a disparity value, with a similar meaning: it measures contigs that are in disagreement with the bins' consensus taxon. In this case we add the "congruent" value, that it is simply disparity = 0, which is probably confusing because it looks like a different measure when it is not.

One obvious thing to do when curating a bin is to spot the contigs that are contributing to disparity, and check if these can be removed safely from the bin. For instance, if you see that when removing that contig, contamination is decreasing but completion remains the same. That would mean that the contig contained a duplicated single copy gene and therefore it is likely to be a contaminant. We have made a couple of utility scripts for doing things like this, you can take a look at  them if you wish. The manual describes how they work.

Best,
Javier

**Comment by gruningerrj** [comment]
Thanks for the response Javier. I really appreciate the excellent support that both you Fernando are providing to users.

Best,
Rob
