### ISSUE TITLE
User configuration (write permission denied)

### ISSUE THREAD

**Issue by dbenaben** [jtamames/SqueezeMeta#295]
Hello,

On our site, SqueezeMeta is installed by administrators (thanks to your conda package).
And users can use`download_databases.pl` or `configure_nodb.pl` script.
But it fails due to scripts that try to write on conda directory environment (_lib_, _lib/checkm_ and _scripts_).
Example:
```
$ download_databases.pl /shared/bank/squeezemeta
[...]
Downloading and unpacking RDP classifier...
--2021-04-30 13:22:04--  http://silvani.cnb.csic.es/SqueezeMeta//classifier.tar.gz
Resolving silvani.cnb.csic.es (silvani.cnb.csic.es)... 150.244.82.96
Connecting to silvani.cnb.csic.es (silvani.cnb.csic.es)|150.244.82.96|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 154722472 (148M) [application/x-gzip]
/shared/ifbstor1/software/miniconda/envs/squeezemeta-1.3.1/SqueezeMeta/lib/classifier.tar.gz: Permission denied

Cannot write to ‘/shared/ifbstor1/software/miniconda/envs/squeezemeta-1.3.1/SqueezeMeta/lib/classifier.tar.gz’ (Permission denied).
Error running command: wget -U '' -P /shared/ifbstor1/software/miniconda/envs/squeezemeta-1.3.1/SqueezeMeta/lib http://silvani.cnb.csic.es/SqueezeMeta//classifier.tar.gz at /shared/ifbstor1/software/miniconda/envs/squeezemeta-1.3.1/SqueezeMeta/lib/install_utils/download_confirm.pl line 37.
```

It would be great if users could download databases and configure SqueezeMeta without any special rights.

**Comment by dbenaben** [comment]
Thanks for your quick reply.

Indeed, it works. But in our site, installations are "automated" on several clusters (thanks to conda or containers). And it's not always easy or possible to download the databases and finalize automatically the configuration.

I think it would be better to separate the configuration part form the binaries. So I wanted to suggest you this improvement, but feel free to close this ticket if it's not relevant for you.

**Comment by fpusan** [comment]
We could think of a way to do that, so that the user can create a local "configuration directory" and then pass it as a parameter during execution. That would avoid the hardcoded configuration we use now. It is not trivial since some of our dependencies (e.g. checkm) also have configuration steps requiring write permissions in the source code directory.

It's not super high priority right now, but I will leave the issue open so we don't forget, maybe we can think of something.

**Comment by fpusan** [comment]
Just a heads up, I've been having success in a cluster by running my own conda environment (which can be configured since it's inside my home directory). Something along this lines works as long as the user's home file can be located from the cluster node. The database can be located wherever.

```
#!/bin/sh -l
#SBATCH STUFF HERE
source /home/user/opt/miniconda3/bin/activate
conda activate SqueezeMeta
cd /path/to/working/directory
SqueezeMeta.pl -s test.samples -f raw/ -m merged -t 8 -p Hadza
```

Possibly you were already aware of this, but maybe it helps?

**Comment by dbenaben** [comment]
Thank you for you feedback.
Yes, we are. If user manage his conda environment, it works. We (administrators) simply would like to install and provide this tool for our users, so the installation is done for all but with special rights. We think about it, we can surely manage this issue on our side also.
