### ISSUE TITLE
Taxonomic classification

### ISSUE THREAD

**Issue by sarpiens** [jtamames/SqueezeMeta#313]
Hello,

I was wondering which is reference genomes for the taxonomic classification used in the pipeline(RefSeq, NT Database, etc) and if the pipeline only supports bacterial and archaeal classification or other groups like viruses and eukariots are also supported?

Thanks in advance!

**Comment by jtamames** [comment]
Hello
SqueezeMeta uses GenBank nr for taxonomic annotation, looking for the most complete reference database. Therefore, eukaryotes and viruses are also included and can be detected. Nevertheless, take into account that the metagenomics pipeline is designed to work with prokaryotes, for instance making use of Prodigal, a prokaryotic gene predictor. Thus, eukaryotes and viruses will be detected but probably with less sensitivity than prokaryotes. If you are interested in these, perphaps you can consider using sqm_reads, since that one works directly with raw reads, skipping assembly and gene prediction.

Best,
Javier

**Comment by sarpiens** [comment]
Thanks for your quick reply!

 I was also wondering if I could use custom databases with this strategy?

Thanks in advance

**Comment by jtamames** [comment]
Yes, sqm_reads also accepts external databases for functional annotations (not taxonomic). Just follow the manual to know how to format your database and how to feed it to SqueezeMeta.
Best,
J

**Comment by sarpiens** [comment]
Okey, thank you very much for you kind reply!
