### ISSUE TITLE
Diamond block size higher then 8

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#315]
Hi,

Is it recommended/possible to use a block size higher then 8 for the Diamond step in SQM? I read in the diamond manual that higher then 20 is not recommended, but I was wondering about values between 8 and 20, have you tried? Or is 8 the maximum possible value when running diamond inside SQM?

Best,
Sam

**Comment by fpusan** [comment]
You can use higher values if you have enough RAM, no problem. I'm not sure whether it will give you more speed, it would be good to know! ;)

**Comment by slambrechts** [comment]
Ok thanks. For now I will continue with 8, because I assume you can not change the `-b` parameter when running `restart.pl`? 

Is it normal for DIAMOND to run for several days with 43 samples and a coassembly of 18 gigabytes in size? I'm using a cluster with 36 threads and 710 GB of RAM

**Comment by jtamames** [comment]
Hello!

You can change the value in the SqueezeMeta_conf.pl file in your project directory. Then restart will take the new value, because it reads the configuration from that file.

User's experience is that Diamond performance is greatly hampered by disk I/O usage. So if you are sharing the cluster with other users and they are also making an intensive use of it, the process will run much slowly.
Nevertheless, you must have many millions of genes to analyze, so it is "normal" that it takes some time to finish. It is not unexpected to spend two or three days on that. After all, you will consume months or even years for analyzing all that once the run is finished.

Best,
Javier

**Comment by slambrechts** [comment]
ok thank you! I can report back that higher values indeed improved speed
