### ISSUE TITLE
Disparity in counts between files

### ISSUE THREAD

**Issue by 3ccasto** [jtamames/SqueezeMeta#320]
Hi,

I'm checking the files 12.project.kegg.stamp and project.KO.abund.tsv and the number of counts for a KEGG identifier is different. For example, for kegg K00001 in the first file the number of counts was of 1344 while in the second was of 1303. Why this happens?

**Comment by fpusan** [comment]
This is weird. I have just checked one of my projects and K00001 has the same abundance in both tables.
I have some suspicions, but it's hard to tell without looking at your project. Can you perhals share it with us?

**Comment by fpusan** [comment]
Hi again., and sorry for the wait!

The disparity occurs because some ORFs have multiple annotations and we deal with that differently in `sqm2tables.py` and in the script that makes the stamp tables....

Most ORFs will have a single annotation, eg: `ORF1    K00001`.
However, a few have multiple annotations: `ORF2    K00001;K00002`

This is not because the protein has multiple hits to `K00001` and `K00002` (that can also happen but we end up reporting a consensus annotation). Instead, it is because some of the proteins in the KEGG reference database actually have two annotations. So a single hit to that reference will give a dual annotation to our ORF.
`sqm2tables.py` and `12.funcover.pl` will deal with this differently when calculating aggregated functional abundances.

1) `sqm2tables.py` (the script that makes the `project.KO.abund.tsv` table among others) divides the mapped reads between the different functions. So if the ORF is annotated as `K00001;K00002` and has 1 mapped read, `K00001` and `K00002` will get 0.5 counts each in the table. This preserves the total number of counts per sample in the final table, but leads to non-integer counts which are counter-intuitive...

2) For the same case described avobe, `12.funcover.pl` (the script that makes the tables for stamp) would just add one count to each of the functions. This does not preserve the total number of counts in the file (a single ORF with one count lead to two KEGG IDs with one count) but it avoids non-integer counts.

The difference is in any case small, since most of the ORFs will have a single annotation.
