### ISSUE TITLE
Can't locate DBI.pm in @INC STEP 6

### ISSUE THREAD

**Issue by lmera** [jtamames/SqueezeMeta#34]
Hello, I'm having this problem at step 6. Both DBI and gcc are installed and I have added them to the $PATH. any ideas to solve this issue?

[0 seconds]: STEP6 -> TAXONOMIC ASSIGNMENT: 06.lca.pl
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /home/leticia/anaconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/leticia/anaconda3/lib/site_perl/5.26.2 /home/leticia/anaconda3/lib/5.26.2/x86_64-linux-thread-multi /home/leticia/anaconda3/lib/5.26.2 .) at /home/leticia/SqueezeMeta-1.0.0/scripts/../scripts/06.lca.pl line 10.
BEGIN failed--compilation aborted at /home/leticia/SqueezeMeta-1.0.0/scripts/../scripts/06.lca.pl line 10.
Stopping in STEP6 -> 06.lca.pl

Thanks :)

Leticia

**Comment by fpusan** [comment]
Hi!
You are missing the DBI perl module.
This is likely because you are inside a conda environment, but you likely installed the required modules in your OS (using apt/yum).
Either run SqueezeMeta outside of conda, or install the required dependencies using conda.

Let me know if that works for you!

**Comment by lmera** [comment]
It worked, thanks!!
