### ISSUE TITLE
Better understanding for Read 1 and Read 2 Merging

### ISSUE THREAD

**Issue by kassammohamed** [jtamames/SqueezeMeta#342]
Hi,

Quick question regarding the final output of the table after sqm2tables step:
I have a sample with 1'250'456 in R1 and 1'250'456 R2.  I am getting when analysis using SQM and plotting with SQM tools in R I am getting an abundance which is the total of R1+R2, question is that SQM is mapping the reads against the contig independently of R1/R2 and then the table is the total of the two reads. Is there an option for paring the reads R1+R2 ?

Thans,

Mohamed

**Comment by jtamames** [comment]
Hello
Not sure if I understand, but you are correct that mapping is done and counted independently for both pairs. This is because it is possible that one of the sequences maps to one contig, and the paired read maps to a different one. If you want to exclude these situations, you could work with samtools and the sam file to remove undesired pairs, then run the 10 script and subsequent ones  to redo the counts.
Best,

**Comment by kassammohamed** [comment]
Ok noted thx for your input.
