### ISSUE TITLE
Removing duplicate reads (100% Identical)

### ISSUE THREAD

**Issue by ATVincent** [jtamames/SqueezeMeta#356]
Hello,

Firstly, thank you for your tool and for maintaining it!

Second, I'd like to get your opinion on removing duplicate reads (100% Identical) and why you haven't introduced this step to SqueezeMeta.

Thank you !

Antony

**Comment by fpusan** [comment]
We found no consensus on whether this is a good practice or not, so we don't force it on the user. This is actually true for the whole data preprocessing steps. We include an option to easily run trimmomatic with sensible parameters, but we believe that there is not a consensus "best filtering" approach, since different experiments and sequencing runs will have different needs.

Of course you can prefilter your reads before running SqueezeMeta if you think that it would improve your analysis.
