### ISSUE TITLE
TPM vs RPKM (to analyze the proportion of community members that encode specific genes)

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#396]
Hi,

In the SQMtools manual I read the part about the `USiCGs Universal Single-Copy Genes`:

> Lists of Universal Single Copy Genes for Bacteria and Archaea. These are useful for transforming
> coverages or tpms into copy numbers. This is an alternative way of normalizing data in order to be
> able to compare functional profiles in samples with different sequencing depths.

I was wondering, if you want to analyze the **proportion** of community members that encode specific genes, you can do that by dividing the read count for those genes (in RPKM or TPM) by the mean of the read counts of those 14 universal single-copy ribosomal marker genes (in RPKM or TPM). But is there a difference whether you use TPM or RPKM for those read counts in this context? I (think I) understand what the difference in general is between TPM and RPKM, but let's say you want to infer the most abundant genes from a list of genes in a community, and be able to say: "This is the most abundant gene, and is present in average xx% of community members, while this gene is present in average xx% of community members).

Or does this differ whether you want to infer the most abundant genes across all samples together, or rather per sample and then take the average?

**Comment by fpusan** [comment]
I don't think it would make a big difference whether you use RPKM or TPM. I normally use TPM rather than RPKM, since it is easier to compare between different samples.

For the normalization you mentioned (which actually I also like using) I would rather divide the coverage of each feature by the median coverage of the single copy genes in that sample. That's actually what we do to generate the `copy_number` tables that are used in SQMtools (but there we only use RecA rather than several USiCGs).

This will give you the average number of copies of that feature (be it a contig, a gene or a function) per genome in your dataset. Note that this can also be applied to subsets of your data. E.g. if you select all genes from Firmicutes, and then do this normalization using only the USiCGs assigned to Firmicutes, this would give you the average copies of the genes per genome in the Firmicutes phylum.

Does this answer your question?

**Comment by slambrechts** [comment]
Ok yes, I think it does, thank you for the info!

> For the normalization you mentioned (which actually I also like using) I would rather divide the coverage of each feature by the median coverage of the single copy genes in that sample.

Any reason/difference between using the coverages vs the tpm to divide each feature by the median of the single copy core genes?

**Comment by fpusan** [comment]
TPM also controls for sequencing depth, but you don't need to do that since you are calculating ratios anyways.
Coverages control by feature length, which is enough.

Aditionally, by default we also include unmapped reads in the TPM calculation. Higher proportion of unmapped reads in one sample will lead to smaller TPMs for all the features in that sample. Should not have a large effect in copy numbe calculation since we are using ratios, but the correct way would be to use coverages directly.

I am aware that some examples in the PDF manual use TPMs for copy number calculation. They come from older versions in which we didn't track coverages in SQMtools. I will have them corrected for next version,

**Comment by fpusan** [comment]
Nevermind, I had already updated the docs previously.
