### ISSUE TITLE
Stopping in STEP1

### ISSUE THREAD

**Issue by alopcat** [jtamames/SqueezeMeta#41]
Good morning.
I am running the provided Hadza dataset to test the program but I keep getting the same error.
I installed the databases using the script _make_databases.pl_ and configured them using _configure_nodb.pl_. 

When I run SqueezeMeta using the following: 

> $LUSTRE/Adri/SqueezeMeta/scripts/SqueezeMeta.pl -m coassembly -p test -s $LUSTRE/Adri/SqueezeMeta/db/test/test.samples -f $LUSTRE/Adri/SqueezeMeta/db/test/raw/ --nopfam -miniden 60

I get this error message:

> restart.pl test
> [0 seconds]: STEP1 -> RUNNING CO-ASSEMBLY: 01.run_assembly.pl (megahit)
> Running assembly with megahit: /mnt/lustre/scratch//home/otras/ini/asm/Adri/SqueezeMeta/scripts/../bin/megahit/megahit  -1 /mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/raw_fastq/par1.fastq.gz -2 /mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/raw_fastq/par2.fastq.gz -t 4 -o /mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/megahit
> 125.0Gb memory in total.
> Using: 113.082Gb.
> MEGAHIT v1.1.3
> --- [Tue Nov  5 12:34:07 2019] Start assembly. Number of CPU threads 4 ---
> --- [Tue Nov  5 12:34:07 2019] Available memory: 134912237568, used: 121421013811
> --- [Tue Nov  5 12:34:07 2019] Converting reads to binaries ---
>     [read_lib_functions-inl.h  : 209]     Lib 0 (/mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/raw_fastq/par1.fastq.gz,/mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/raw_fastq/par2.fastq.gz): pe, 39159256 reads, 100 max length
>     [utils.h                   : 126]     Real: 49.6343 user: 29.0630   sys: 4.3954     maxrss: 154152
> --- [Tue Nov  5 12:34:57 2019] k-max reset to: 119 ---
> --- [Tue Nov  5 12:34:57 2019] k list: 21,29,39,59,79,99,119 ---
> --- [Tue Nov  5 12:34:57 2019] Extracting solid (k+1)-mers for k = 21 ---
> Error running command:    /mnt/lustre/scratch//home/otras/ini/asm/Adri/SqueezeMeta/scripts/../bin/megahit/megahit  -1 /mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/raw_fastq/par1.fastq.gz -2 /mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/raw_fastq/par2.fastq.gz -t 4 -o /mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/megahit at /mnt/lustre/scratch//home/otras/ini/asm/Adri/SqueezeMeta/scripts/../scripts/01.run_assembly.pl line 83.
> Stopping in STEP1 -> 01.run_assembly.pl (megahit)

Any advice will be welcomed.
Thank you, 
Adrián.

**Comment by jtamames** [comment]
Hello!
Apparently megahit crashed for unknown reason. Could you please attach or copy the file data/megahit/log that you will find in your 'test' directory?
Best,

**Comment by alopcat** [comment]
Here I attach the content of that file

> MEGAHIT v1.1.3
> --- [Thu Nov  7 09:05:19 2019] Start assembly. Number of CPU threads 12 ---
> --- [Thu Nov  7 09:05:19 2019] Available memory: 134916599808, used: 121424939827
> --- [Thu Nov  7 09:05:19 2019] Converting reads to binaries ---
> /mnt/lustre/scratch/home/otras/ini/asm/Adri/SqueezeMeta/bin/megahit/megahit_asm_core buildlib /mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/megahit/tmp/reads.lib /mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/megahit/tmp/reads.lib
>     [read_lib_functions-inl.h  : 209]     Lib 0 (/mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/raw_fastq/par1.fastq.gz,/mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/raw_fastq/par2.fastq.gz): pe, 39159256 reads, 100 max length
>     [utils.h                   : 126]     Real: 51.6705	user: 29.8707	sys: 4.8841	maxrss: 154340
> --- [Thu Nov  7 09:06:11 2019] k-max reset to: 119 ---
> --- [Thu Nov  7 09:06:11 2019] k list: 21,29,39,59,79,99,119 ---
> --- [Thu Nov  7 09:06:11 2019] Extracting solid (k+1)-mers for k = 21 ---
> cmd: /mnt/lustre/scratch/home/otras/ini/asm/Adri/SqueezeMeta/bin/megahit/megahit_sdbg_build count -k 21 -m 2 --host_mem 121424939827 --mem_flag 1 --gpu_mem 0 --output_prefix /mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/megahit/tmp/k21/21 --num_cpu_threads 12 --num_output_threads 4 --read_lib_file /mnt/lustre/scratch/home/otras/ini/asm/Adri/Scripts/Squeeze/test/data/megahit/tmp/reads.lib


Thank you very much for your reply.

**Comment by fpusan** [comment]
We have updated the version of megahit redistributed with SqueezeMeta to v1.2.9. Apparently the 1.2 branch solved several memory errors, and maybe this is one of them (the log is not showing any specific error, so it's hard to know, but worth a try).

Please pull the latest version from master and start a new project from scratch with the test samples.

**Comment by alopcat** [comment]
First steps are running with the new version. Thank you very much for your help.

**Comment by Sewunet-Abera** [comment]
Hello there,
I'm really enjoying working on SqueezeMeta.
Initially I run my data set (69 samples, 225GB size) with default settings. 
But due to >70% of unmapped reads I set the mapper to bwa, --D flag and --euk to focus on prokaryotes and treat unmapped as contigs. but run into this error as above:

Running assembly with megahit
Error running command:    /home/nioo/sewuneta/.conda/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit  -1 /home/nioo/sewuneta/sorghum_shotgun_metagenome_analysis/SqueezeMeta/sqmeta5/data/raw_fastq/par1.fastq.gz -2 /home/nioo/sewuneta/sorghum_shotgun_metagenome_analysis/SqueezeMeta/sqmeta5/data/raw_fastq/par2.fastq.gz -t 40 -o /home/nioo/sewuneta/sorghum_shotgun_metagenome_analysis/SqueezeMeta/sqmeta5/data/megahit >> /home/nioo/sewuneta/sorghum_shotgun_metagenome_analysis/SqueezeMeta/sqmeta5/syslog 2>&1 at /home/nioo/sewuneta/.conda/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_assembly.pl line 119.
Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the sqmeta5/syslog file (zip it first)

Then following the above issue tried to git pull but I think I'm missing something and got the error below  
sewuneta@nioo0003:~/sorghum_shotgun_metagenome_analysis/SqueezeMeta$ git pull SqueezeMeta
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


Thanks in advance
