### ISSUE TITLE
SqueezeMeta_conf.pl and flye 2.9 errors

### ISSUE THREAD

**Issue by GiangLeN** [jtamames/SqueezeMeta#417]
Hi,

I upgraded to the latest version for flye 2.9 for my analysis but encountered a few issues.

The first is: 
`Can't open /home/giang.le/anaconda3/envs/squeezemeta/SqueezeMeta/scripts/SqueezeMeta_conf.pl`

After renaming SqueezeMeta_conf_original.pl to SqueezeMeta_conf.pl, the program seems to run.

The second issue I found is with flye 2.9 as it fails to run minimap2.

Please find attached syslog file.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/7903577/syslog.zip)

Also, I installed squeezemeta through mamba.

Giang

**Comment by fpusan** [comment]
Regarding the problem with `SqueezeMeta_conf.pl`, renaming the `SqueezeMeta_conf_original.pl` is not the right solution. Since you installed a new version, please refer to section 12 of the ReadMe file

> 12. Updating SqueezeMeta
Assuming your databases are not inside the SqueezeMeta directory, just remove it, download the new version and configure it with
/path/to/SqueezeMeta/utils/install_utils/configure_nodb.pl /path/to/db

Running `configure_nodb.pl` will create the right SqueezeMeta_conf.pl file for you. You will of course need to change the name of the file to `SqueezeMeta_conf_original.pl` for this to work.

Check whether this fixes the first issue. Meanwhile I'll take a look at the missing minimap problem.

**Comment by GiangLeN** [comment]
> Regarding the problem with `SqueezeMeta_conf.pl`, renaming the `SqueezeMeta_conf_original.pl` is not the right solution. Since you installed a new version, please refer to section 12 of the ReadMe file
> 
> > 12. Updating SqueezeMeta
> >     Assuming your databases are not inside the SqueezeMeta directory, just remove it, download the new version and configure it with
> >     /path/to/SqueezeMeta/utils/install_utils/configure_nodb.pl /path/to/db
> 
> Running `configure_nodb.pl` will create the right SqueezeMeta_conf.pl file for you. You will of course need to change the name of the file to `SqueezeMeta_conf_original.pl` for this to work.
> 
> Check whether this fixes the first issue. Meanwhile I'll take a look at the missing minimap problem.

The first issue is fixed after I run the recommended command.

**Comment by fpusan** [comment]
The second issue has hopefully been fixed in c9cc72b. I released version 1.5.1, please update (make sure to run `configure_nodb.pl` when you do) and let me know if it works now!

**Comment by GiangLeN** [comment]
The issue is fixed. Thank you for your time.

**Comment by fpusan** [comment]
Glad to hear, closing
