### ISSUE TITLE
Error while loading data in R with SQMtools

### ISSUE THREAD

**Issue by enormandeau** [jtamames/SqueezeMeta#446]
We're trying to use `SQMtools::loadSQM()` on our data an are getting the following error:

```
zebra = SQMtools::loadSQM("zebrafish_coassembly_run")
Generating tabular outputs for project in zebrafish_coassembly_run
Loading orfs
    table...
    abundances...
    sequences
    taxonomy...
Loading contigs
    table...
    abundances...
    sequences...
    taxonomy...
    binning info...
Aggregation function missing: defaulting to length
Error in dim(ordered) <- ns : 
  dims [product 275146] do not match the length of object [11003601]
```

Is this something you have come across? Would you have any idea on how to solve this?

**Comment by fpusan** [comment]
It has happened a couple of times, see #437 . 
As stupid as it may sound, in that case the issue eventually solved itself after trying `loadSQM` several times.
This is an elusive problem.  It will happen only for some datasets and some installations, and even then it doesn't happen all the time.

Some things that would be great to check would be:
1) did you restart the project at any point?
2) does the issue happens again if you re-run the project?
3) can you share the `/path/to/project/intermediate/18.*.contigsinbins` file with me?

Otherwise, let me know if you manage to get it working by sheer repetition. Otherwise I will ask you to share your project with me so I can try to reproduce the issue in my system.

**Comment by enormandeau** [comment]
Thank you for the response. I am trying to re-run the code.

This analysis was launched more than one time but the output folder was completely deleted before each run.

It would take 3-4 days to rerun this project. I will try this if it doesn't work. I have 4 other projects that I ran SqueezeMeta with so I will also try these.

I tried this one first because it is the smallest one. The output folder weights in at about 513GB.

Attached is the `18.*.contigsinbins` file.

[18.zebrafish_coassembly_run.contigsinbins.zip](https://github.com/jtamames/SqueezeMeta/files/8334928/18.zebrafish_coassembly_run.contigsinbins.zip)

**Comment by enormandeau** [comment]
Launching it repeatedly did work after 4 times!

I'll try the other projects and re-open this issue if needed.

Thank you.

**Comment by fpusan** [comment]
Glad it worked for you. Though I'd rather see it failing consistently that working inconsistently u_u
I have tried running the part of the code that fails on the file you sent me and it is working ok for me. A bit of a surprising thing is that all the contigs were assigned to a single bin ("maxbin.002"). What kind of data are you running?

**Comment by enormandeau** [comment]
The VERY big majority of the sequences are from the host fish.

**Comment by fpusan** [comment]
Ah, the horror of host-associated samples... been there
