### ISSUE TITLE
Running with externally supplied metagenome assemblies

### ISSUE THREAD

**Issue by arjun-1985** [jtamames/SqueezeMeta#462]
hello team I am trying to run the squeezemeta with the externally supplied assembled reads, but the programme is getting closed abruptly. I am attaching the system log for your referenc
[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/8462371/syslog.txt)
e

**Comment by fpusan** [comment]
Hi,
From your input command
`/home/arjun/miniconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl -m merged -p k -s /home/arjun/export/test/test.samples -f /home/arjun/export/test/raw --nopfam -miniden 50`

It looks like you want to treat your contigs as if they were input reads. This may be crashing megahit (maybe because it expects inputs to be in the fastq format?). You can combine all your fasta files into one and then use it as input using the ' --extassembly` flag, please check the documentation for more details.

**Comment by jtamames** [comment]
Hello
Apparently you have 4 assemblies and you want to merge them, is that correct?
Try putting these 4 fasta files in the intermediate directory, then run `01.merge_assemblies.pl k` (since k is your project name). When it finishes and you see a 01.k.fasta file in your results directory, restart SqueezeMeta in step 2: `restart.pl k -step 2`
And you need to change your samples file because you need to specify the raw reads that you used for the assembly. Otherwise there is no way to calculate mappings and coverages and the run will stop.
Best,

**Comment by arjun-1985** [comment]
Hello,
The four assemblies, are belonging to four different samples, and if we merge them can we get the separate binning for each and every samples, please help me in this regard. Due to my basic understanding of linux commands, I am not able to run 01.merge_assemblies.pl, command. I am attaching the sample file for your refernce. Kindly see where I am getting worng, please help, as I am struggling for very long time
[test.samples.txt](https://github.com/jtamames/SqueezeMeta/files/8463392/test.samples.txt)
.

**Comment by jtamames** [comment]
Hello
If you merge the four assemblies you will have bins that can be present in one, some, or all samples.
Your samples file must contain raw reads, not the contigs resulting from the assembly. Otherwise how could you estimate the abundance of the genes and contigs, if you don't know how many reads compose each of these contigs/reads? If you don't have the raw reads, then you could not estimate abundances nor do binning. I recommend you to use sqm_annot.pl in that scenario.
Nest,
