### ISSUE TITLE
Why don't transform the sam files to bam format?

### ISSUE THREAD

**Issue by linfanxiao** [jtamames/SqueezeMeta#514]
Hello,

I have a SqueezeMeta run that just finished. Some extensive data has been generated ( most of them are sam files). I wonder why squeezemeta doesn't choose the bam files as the final results to save spaces?  I know users can transfer the sam files to bam files via samtools or sambamba by themselves. It can add some steps to transform these files automatically in the squeezemeta pipeline?

Thank you!

Eric

**Comment by fpusan** [comment]
That is actually implemented already but we don't do it by default because in some modes we need the sam file later.

You can make it work easily.

1) Find the location of script 10 with `which 10.mapsamples.pl` (in in conda) and edit it
2) Near line 190 you will find the following
```
	if(0) {
		my $ecode = system("$samtools_soft sort $outsam -o $samdir/$projectname.$thissample.bam -@ $numthreads; rm $outsam");
                if($ecode!=0) { die "Error running samtools"; }
	}
```

3) Edit the first line so it is `if(1)`

Hope it works for you!

**Comment by linfanxiao** [comment]
Thanks for the response! I will edit the script!
