### ISSUE TITLE
functional annotation for bins

### ISSUE THREAD

**Issue by shashankx** [jtamames/SqueezeMeta#52]
Hi,
Can we do the functional annotation for the Bins extracted from other tools? for example prediction of kegg and metacyc patwhays for each bin ?
Thanks

**Comment by jtamames** [comment]
Hello!
If you mean using the contigs produced by SqueezeMeta but binned externally, yes, you can change the %dasdir hash in the SqueezeMeta_conf.pl script in the project directory, making it point to the directory where you have the contigs. Then restart SqueezeMeta using restart.pl -step 17, to proceed with bin annotation. Or, if you want to use several extrnal binning results combining them with DAS Tool, change the %bindirs hash in the same SqueezeMeta_conf.pl script, and then restart.pl -step 16.

But if you mean annotating a set of contigs not produced by SqueezeMeta, then I am sorry, there is now way to do it at this moment.

Best,
Javier

**Comment by jtamames** [comment]
I now realize that it would be possible to use your contigs if you run SqueezeMeta using the -ext-assembly flag to privide the fasta with the contigs. And when the analysis is complete, you do what I told you above: change either the %bindirs or %dasdir directories and restart SqueezeMeta from step 16 in the first case, or 17 in the second.

Best,
Javier

**Comment by shashankx** [comment]
Hello Javier,

Thank you for the quick reply.

So, after keeping the bins in a directory and changing the %dasdir hash in the SqueezeMeta_conf.pl script (path to the bin directory) and restart the SqueezeMeta using `restart.pl -step 17`, this will only perform the following-

> - Taxonomic assignment of bins, and check for taxonomic disparities
> - Checking of bins with CheckM
> - Merging of previous results to obtain the bin table
> - Merging of previous results to obtain the contig table
> - Prediction of kegg and metacyc patwhays for each bin
> - Final statistics for the run

And as you mentioned while running the SqueezeMeta with flag `-ext-assembly` where I keep all the assemblies generated externally.

Secondly, can we also add CheckM results along with this, as I have already calculated the quality of the bins? 

Please correct me if I am wrong. 

Best,
Shanky

**Comment by jtamames** [comment]
Hello 

That´s correct if you use the SqueezeMeta contigs. But if you want to use your own set of contigs, use the -ext-assembly flag and SqueezeMeta will do the rest of the analysis, that is, gene prediction, gene and contig annotations, mapping of reads and estimation of abundances.

CheckM is mandatory in the binning step and there is no way to use external checkm results. Nevertheless the results must be coincident. The only difference is that SqueezeMeta uses its own bin annotation to provide the taxon name for checkM, instead of letting it to figure it out.

I cannot tell how much is goint to take, it will depend very much of your computing environment. You already have the bins that is the most demanding part, so much of the time will go in running checkM.

Best,
Javier

**Comment by shashankx** [comment]
Thank you for clearing that.
Just to be clear that I understood correctly, the following command should do the trick-
Mode should be **sequential**? Because I don't need to create bins, right?

```
perl ./scripts/SqueezeMeta.pl -t 280 -m sequential -p HumanGutMetagenome -f ../fastq_files/ -s samples -extassembly ../Assembly/

ls ../fastq_files/ | head
18097D-02-01_1.fastq
18097D-02-01_2.fastq
18097D-02-02_1.fastq
18097D-02-02_2.fastq

head samples
Sample18097D0201        18097D-02-01_1.fastq    pair1
Sample18097D0201        18097D-02-01_2.fastq    pair2
Sample18097D0202        18097D-02-02_1.fastq    pair1
Sample18097D0202        18097D-02-02_2.fastq    pair2

ls ../Assembly/ | head
18097D-02-01_Assembly_final_assembly.fasta
18097D-02-02_Assembly_final_assembly.fasta
```

**Comment by jtamames** [comment]
Hello
Mode should be coassembly, because you want to take advantage of the differential abundance of the same contigs in the different samples. But for that you need just one fasta file containing the coassembly (notice that for the argument of the -extassembly flag if the fasta fie containing the assembly, not the directory). Could you please explain how you did your binning? I want to be sure that I am understanding it rigth

Best

**Comment by shashankx** [comment]
Hello Javier,
I have done the binning using [MetaWrap ](https://github.com/bxlab/metaWRAP/blob/master/Usage_tutorial.md#step-4-bin-the-co-assembly-with-three-different-algorithms-with-the-binning-module) using three method metabat2, maxbin2, concoct. I have not done co-assembly, instead, I did binning for individual samples separately.

Therefore, for 500 metagenome samples, I have 500 assemblies (using MetaSPades) and approx 4200 bins in total from all 500 samples.

The main idea right now is to annotate these bins (4200) using KEGG or metacyc.
Best

**Comment by jtamames** [comment]
Ok, I understand now. I thougth you had one single assembly coming from different metagenomes. Then you cannot use SqueezeMeta in the way I told you yesterday, because the -extassembly flag does not accept several assemblies. You could create a shell script for running SqueezeMeta for every single metagenome you have, providing the appropriate contig file for each with -extassembly and specifying --nobins since you already have bins. 

So, for each bin you create a samples file with the read files of the corresponding metagenome, and run SqueezeMeta in sequential mode using that samples file and the -extassembly flag pointing to the fasta containing your bin. You will do some not needed extra steps, such as mapping abundances of reads. It should work but it is not the intended use of the pipeline. Have you considered using a dedicated genomic annotation software, such as Prokka? Maybe it suits your needs better.

Best,
Javier

**Comment by shashankx** [comment]
Thank you for the details.
Indeed! Prokka will do the job for me. Nevertheless, I will give SqueezeMeta a try.
Best
