### ISSUE TITLE
nr.db is missing or corrupt?

### ISSUE THREAD

**Issue by sskoldas** [jtamames/SqueezeMeta#523]
Hi,

I have two questions. First, I installed SqueezeMeta using make_database.pl yesterday. Version 1.4.0 was installed, how can I get latest version?
Second question is that after running test_install.pl, I got a warning that I added below and also shared contents of the downloaded database as a screenshot. How can I fix this warning?   

Thank you

> WARNING: Some SqueezeMeta dependencies could not be found in your environment!
	SqueezeMeta_conf.pl says that databases are located in /media/sskoldas/3E4A56A74A565C29/squeezemeta_db/db but we can't find nr.db there, or it is corrupted
![Screenshot from 2022-08-10 06-29-38](https://user-images.githubusercontent.com/55446435/183806865-9e215ccc-840d-4597-b72e-e78848350f9a.png)

**Comment by fpusan** [comment]
Hi!
1) Running `make_databasesl.pl` will not install SqueezeMeta, just compile a new database from the source data. To have the newest version just install SqueezeMeta again with conda in a fresh environment (you can overwrite your current one if you want to)
2) From your screenshot I can see that the `nr.gz` file was not uncompressed, most likely because the download failed midway. This is a problem I have experienced myself, but we can not fix it: we download that file from NCBI's servers, which sometimes don't work as expected. In my case, `make_databases.pl` worked at the second try. However you can just run `download_databases.pl` instead. This will download a pre-compiled database from our servers.
