### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by Jokendo-collab** [jtamames/SqueezeMeta#524]
I am running SqueezeMeta on HPC and I am getting the following error:

`Dear ilifu slurm user,`

`Your job 4361185 (squeezMeta) has changed state:`
      `Run time 00:26:24, OUT_OF_MEMORY`
`Kind regards,`
`ilifu Slurm Scheduler.`

How can I go around this error?

**Comment by fpusan** [comment]
1) Use the latest version of SqueezeMeta, we have some improvements in that regard
2) Allocate enough memory when requesting the job in your cluster
3) Manually set up DIAMOND memory usage by adding `-b 8` (for example, see the ReadMe for more details on this)
4) Otherwise check with your HPC administrator

**Comment by Jokendo-collab** [comment]
@fpusan Thanks for this. I installed this software today and I am assuming that it's the latest version. I will try your suggestions and let you know how it goes
