### ISSUE TITLE
Analysis stuck for over two days!

### ISSUE THREAD

**Issue by Jokendo-collab** [jtamames/SqueezeMeta#525]
I only have 12 samples which I started working on two days ago. The program is stuck and I am not if this is normal. Can someone confirm this?

SqueezeMeta v1.5.1, Jan 2022 - (c) J. Tamames, F. Puente-SÃ¡nchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349
Run started Sat Aug 13 18:44:23 2022 in coassembly mode
Now creating directories
Reading configuration from /cbio/users/javanokendo/sarsCovProject/art_variantAnalysis/tmp_metagenomics/analysis_results/SqueezeMeta_conf.pl
Reading samples from /cbio/users/javanokendo/sarsCovProject/art_variantAnalysis/tmp_metagenomics/analysis_results/data/00.analysis_results.samples
12 samples found: SRR12670008 SRR12670013 SRR12670011 SRR12670006 SRR12670016 SRR12670012 SRR12670015 SRR12670007 SRR12670010 SRR12670017 SRR12670009 SRR12670014

Now merging files
[4 minutes, 14 seconds]: STEP1 -> RUNNING CO-ASSEMBLY: 01.run_assembly.pl (spades)
  **Running assembly with spades**

**Comment by fpusan** [comment]
It might be normal, depending on how many cores you are using.
As long as spades is progressing (even if it does so slowly) I wouldn't worry.
You can check the progress in the `syslog` file inside the project directory.
Also internal spades logs can be found in the `data/spades` directory inside the project directory.
Alternatively you can use megahit as the assembler, since it is less resource intensive...
