### ISSUE TITLE
Subsets of sqm_longreads.pl projects

### ISSUE THREAD

**Issue by bojusemo** [jtamames/SqueezeMeta#528]
Hello,

I have plenty of projects obtained with sqm_longreads.pl . Now I need to load them in R and filter out some taxas, functions and bins. To do so, I'm trying to load the projects  to R with the function loadSQM of the SQMTools package. However, I receive an error saying it is not a valid SqueezeMeta project.

Could you please let me know how to combine plenty of sqm_longreads.pl projects and filter out taxas, functions and bins? I would like to do that in R, but I could try another environment if you think there is a better option.

Regards

Boris

**Comment by fpusan** [comment]
`sqm_reads.pl` and `sqm_longreads.pl` must be loaded using the `loadSQMlite` function in SQMtools.

Subsetting these projects has been supported since v1.5.0, but it can not be done inside SQMtools. Rather, it is done when calling `sqmreads2tables.py`. Call `sqmreads2tables.py --doc` for details on the filtering syntax.

This will produce a directory of tables with the subsetted project, that you can then load into R using `loadSQMlite`. Different `SQMlite` objects can be combined using the `combineSQMlite` functions.

**Comment by bojusemo** [comment]
Thank you doe your answer,

I already ran my projects with the v1.4 of SqueezeMeta. 

Does your solution works if I install v1.5 and use sqmreads2tables.py of v1.5 on the projects obtained with v1.4?

**Comment by fpusan** [comment]
I am not entirely sure but I think it might be fine, I would definitely try that.

**Comment by bojusemo** [comment]
Thank you so much,

I'll try that.

**Comment by bojusemo** [comment]
Hi @fpusan,

Your solution worked for me. Thank you.

An update: When you type sqmreads2tables.py --doc , the documentation has a typing mistake. Instead of referring to sqmreads2tables.py, it mentions sqm**_**reads2tables.py (with an underscore symbol).

Regards

Boris

**Comment by fpusan** [comment]
Glad to hear it worked and thanks for reporting the typo in the docs! I just fixed it :)
