### ISSUE TITLE
Associating taxonomic profile to annotated functions in SQMobjects

### ISSUE THREAD

**Issue by tsa4a12** [jtamames/SqueezeMeta#530]
According to the Wiki, the SQMobject contains the functional and taxonomic abundance separately, but when I try to link the two data (like for making a graph showing the relationship of tax vs fun) the information seems not directly contained in the data structure.

The easiest data I can get are the overall taxonomic profile for a gene set/ vice versa, but the links between them are obscured

However, as I could freely subset the SQMobject by fun/tax, theoretically I should be able to derive the functional abundance each SINGLE taxa has for a gene set (or vice versa), and unfortunately seems there is not yet a more direct way to link the two.

As I am using an old version of SQM/SQMtools (V1.4.0/0.6.2), I wonder if it is a feature on the newer SQM data structure, or if there are better ways to do this?

Anyways, thank you so much for developing such a great tool!

Thanks,
Tom

**Comment by fpusan** [comment]
> However, as I could freely subset the SQMobject by fun/tax, theoretically I should be able to derive the functional abundance each SINGLE taxa has for a gene set (or vice versa), and unfortunately seems there is not yet a more direct way to link the two.

Indeed, that would work and it is the easy way to do it.

The information to do it yourself is actually present in the SQM object.
1) Let's say you want to investigate relationships between KEGG IDs and taxonomic profiles.
2) The KEGG ID for each ORF can be found at `SQM$orfs$table[,'KEGG ID']` (one row per ORF). Other columns in that table will contain classifications according to the COG database, the PFAM database, or other custom databases that you added when running SqueezeMeta.
3) The taxonomic profile for each ORF can be found at `SQM$orfs$tax` (one row per ORF, one column per taxonomic rank).
4) The raw abundances for each ORF can be found at `SQM$orfs$abund`. Other ways to normalize the abundances (coverage, tpms...) will also be available inside `SQM$orfs`.

By combining this information you should be able to get what you want. Internally, `subsetFun`, `subsetTax` and `subsetBins` will also do that, with other bells and whistles (e.g. using contig taxonomy instead of ORF taxonomy in some cases).
