### ISSUE TITLE
SqueezeMeta output

### ISSUE THREAD

**Issue by aalkin2001** [jtamames/SqueezeMeta#536]
Hello,

I analyzed my data generated from the ONT MK1C sequencer. I am just wondering whether it's possible to generate a phylogenetic tree from any of the output files, if yes, which of the file and how?

Also, I want to know which of the files will contain all identified bacteria taxa in different samples.

Thank you,

**Comment by fpusan** [comment]
No, it is not possible to create phylogenetic trees from the output files (at least not without expert knowledge, which we can not provide here).

In order to obtain the bacterial taxa in the different samples, you can run `sqm2tables.py /path/to/project /path/to/project/tables`

The `/path/to/project/tables` directory will contain lots of files. Those with `prokfilter` in the names contain the bacterial composition of the samples at different taxonomic levels.
