### ISSUE TITLE
How to run in hybrid mode and how to pass multiple external assemblies into SqueezeMeta?

### ISSUE THREAD

**Issue by gaworj** [jtamames/SqueezeMeta#561]
Hi, 
Thank you very much for such amazing pipeline.

Is it possible to run metaspades assembly in Squeezemeta in hybrid mode as it is done for example in Atlas metagenomic pipeline?

I would like to assemble Illumina + ONT data and don't want to use canu or flye.

Second question is related to passing the external assemblies into SqueezeMeta.

How to set analysis of multiple assemblies at once?

Something like this:

SqueezeMeta.pl -t 64 -m sequential -f input/ -s samples_file.txt -extassembly input/sample-2_final_contigs.fasta -extassembly input/sample-3_final_contigs.fasta -extassembly input/sample-4_final_contigs.fasta

My sample file looks like this:

sample-2	sample-2_final_contigs.fasta	pair1
sample-3	sample-3_final_contigs.fasta	pair1
sample-4	sample-4_final_contigs.fasta	pair1

Sorry for such silly questions but I'm a little bit lost even after reading the wiki.

Thank you for your help in advance.

Bests,
Jan

**Comment by jtamames** [comment]
Hello Jan
You can specify parameters for SPAdes in the command line of SqueezeMeta, but currently there is no way to specify different sets of reads. In that case, perform the assembly externally and then provide it to SqueezeMeta via the -extassembly option

Regarding the analysis of multiple assemblies, this can be done by specifying the "extassembly" option in the samples file. Please check the section devoted to the samples file in the page 10 of the manual to find an example. It is usually better to check the manual instead of the wiki, since all detailed information regarding the functioning of the pipeline can be found there.

Best,
Javier
