### ISSUE TITLE
MetaCyc pathways

### ISSUE THREAD

**Issue by astromecki** [jtamames/SqueezeMeta#585]
Hello,

I am hoping to explore the MetaCyc pathways generated in step 20. Is there a way to work with these data in R/SQMtools, for ex. writing a table similar to the KEGG pathway table in sqm2tables.py?

Thanks,
Amanda

**Comment by fpusan** [comment]
No, sorry, we do not support this at the moment. The results from minpath are a rough guide, but we recommend to manually curate pathway level analyses, as automated pathway prediction can be sometimes tricky.

**Comment by astromecki** [comment]
Understood. Thank you very much!

Best,
Amanda

**Comment by sheaster** [comment]
Hello, I was wondering if you could expand on what you mean by noisy and overprediction for the metacyc pathways from minpath? 
Is this because of the mapping from KOs to ECs is not perfect with respect to metacyc?
thanks!

**Comment by fpusan** [comment]
Yes, but also because it is not trivial to predict presence/absence of a whole pathway in an automated fashion.
Several reactions participate in more than one pathway so their presence is not diagnostic. Other reactions may have been misannotated or failed to assemble so they are not present in your dataset even if they were really in your community...

MetaCyc does takes this into account on their PATHOLOGIC algorithm (more details [here](https://biocyc.org/013-ptools-pathologic.shtml)) but we've found instances in which their predictions are wrong. Also I am not sure to what extent MinPath implements the full PATHOLOGIC algorithm.

When I want to discuss a certain pathway I look in the literature for the most commonly discussed genes (normally corresponding to terminal reactions in a pathway, since they are normally quite specific) and focus on those rather than using automated pathway annotation.
