### ISSUE TITLE
Restart from STEP 6. lca.pl

### ISSUE THREAD

**Issue by Lafmas** [jtamames/SqueezeMeta#596]
Hello.

During the analysis, my process died at step 10. So I used restart commands after the number of threads was lowered.

However, it was restarted at step 6., not at step 10.

I want to know if this is because of my initial command option.

At the initial start, the command is "SqueezeMeta.pl -m coassembly -p path -s @@.tab -f @@ -t 50 --doublepass --nocog --nopfam --euk" 

The command used to restart is "SqueezeMeta.pl -p path --restart".

thank you

**Comment by jtamames** [comment]
Hello
In the last version, if you invoke restart without a step number, it will redo all missing results. It is likely that we have a bug here because the doublepass flag creates a new taxonomic assignment file replacing the one in step 6. This is why it is trying to recreate it. I would look into this. In any case, you can run restart with --step 10 to skip all previous steps.
Best,
J

**Comment by Lafmas** [comment]
Thanks for your quick reply.

Even if the analysis proceeds, is there any problem with the final result? If there is a problem, I will stop the analysis (e.g. kill -9) and enter the restart command correctly.

thank you

**Comment by jtamames** [comment]
It should work correctly both ways
Best,

**Comment by Lafmas** [comment]
Thank you for your kind reply. Questions were resolved.

I will continue my analysis.

thank you

Closed the issue
