### ISSUE TITLE
Running individual script of the pipeline

### ISSUE THREAD

**Issue by MariaVetcos** [jtamames/SqueezeMeta#67]
Hello, 
I have a query regarding use of SqueezeMeta. I have done my analysis till binning using metabat from outside the pipeline SqueezeMeta. Now I want to continue with the pipeline in the mid(after metabat). But I am getting an error "Can't find SqueezeMeta_conf.pl in BjSa_G210. Is the project path ok? at /data/bin/SqueezeMeta-v1.0.0/SqueezeMeta/scripts/16.dastool.pl line 15.
srun: error: slurm-n5: task 0: Exited with exit code 2"
If anyone can help me out to sort this problem.
I am new to metagenome analysis so I need your help if you can.
Thank you,

**Comment by jtamames** [comment]
Hello Maria
The intended way of running the pipeline is running the SqueezeMeta.pl script that will create, amongst other, the SqueezeMeta_conf.pl file storing all information regarding the run. This file is used for all the other scripts in the pipeline to know the name and location of intermediate results and tools. 
I am afraid it is not going to be easy to start in step 16 from scratch, because further scripts will try to read previous results that you won´t have. For instance, it will try to provide a taxonomic annotation for the bins using the taxa from the contigs, and you won´t have that. It will attempt to run checkM using the bin taxonomic annotation, then it will fail there as well. And so on.

I suggest you either to run the full analysis using SqueezeMeta, or to run DASTool by itself (outside the pipeline) with the metabat and maxbin results that you already have.

Hope it helps. Best,
Javier

**Comment by jtamames** [comment]
Closed by inactivity
