### ISSUE TITLE
Error on Step6

### ISSUE THREAD

**Issue by kassammo** [jtamames/SqueezeMeta#7]
Hello,

I am having an error on step6 LCA 
[0 seconds]: STEP6 -> TAXONOMIC ASSIGNMENT: 06.lca.pl
DBD::SQLite::db prepare failed: disk I/O error at /home//metagenomics/2_Scripts/SqueezeMeta/scripts/../scripts/06.lca.pl line 157, <infile2> line 26.
DBD::SQLite::db prepare failed: disk I/O error at /home//metagenomics/2_Scripts/SqueezeMeta/scripts/../scripts/06.lca.pl line 157, <infile2> line 26.

Any thing wrong ?

Thanks,

Mohamed

**Comment by fpusan** [comment]
Dear Mohamed,

It looks like the LCA database is locked, which it shouldn't since it doesn't get written to after it is created by the make_databases.pl script. Here are some questions for you:

- Which operating system are you using?
- Did you install the databases using the make_databases.pl script?
- Were the databases installed in a remote filesystem?
- Is your disk full, or close to being full?
- Can you download the latest version of SqueezeMeta (v0.4.2) and re-build the database? In the latest version, the make_databases.pl script should print an error message if there is a problem with the creation of that particular file.

Best,

Fernando

**Comment by kassammo** [comment]
Dear Fernando,

So I am getting this error when making the database

  Running nrindex.pl
File created: /home/kassammo/metagenomics/1_Input/metaG/SqueezeMeta/db/LCA_tax/nr.taxlist.db

  Running taxid_tree.pl
File created: /home/metagenomics/1_Input/metaG/SqueezeMeta/db/LCA_tax/taxid_tree.txt

  Creating sqlite databases

Error: near line 1: disk I/O error
Error: disk I/O error
Error: near line 1: disk I/O error
Error: near line 1: disk I/O error
Error: disk I/O error


Thanks,

Mohamed

**Comment by fpusan** [comment]
Dear Mohammed,

So a similar problem appears... StackOverflow thinks that this is most likely due to disk problems, rather than an specific issue with SQLite3.

We tested this script last week, and worked fine in Ubuntu14, Ubuntu18 and CentOS7. NCBI hasn't added a new release since last tuesday, I'll re-create the database on my side just to be 100% sure that nothing has broken since last week, but I'm pretty sure that the problem is in your end.

So what about the rest of my questions?
- Which operating system are you using?
- Were the databases installed in a remote filesystem?
- Is the disk holding the databases full, or close to being full?

**Comment by kassammo** [comment]
Dear Fernando,
I have tried again with the new version of scripts but still same issue.
to answer your questions :
I am using rhel fedora (CentOS Linux 7), the data are stored in file system and the disk are not full at all.

Thanks,

Mohamed

**Comment by fpusan** [comment]
Dear Mohammed,

Just to keep discarding possible issues:
* Are you running Fedora in a VM or is it your native OS?
* Did you install the database with sudo? Does your user have read permissions to the database folder?
* Does the file `your_project_path/results/04.*.nr.dmnd`contain hits to the database? I would assume it does, but just checking.

As a temporal workaround, does your institution have any ftp server so that we can send you our database built and tested in CentOS7?

**Comment by fpusan** [comment]
Closed, as it should be solved with the switch to pre-compiled databases in v0.4.3.
