### ISSUE TITLE
Are the rRNA gene sequences removed?

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#712]
Hi, thanks for your excellent pipeline. I am wondering if the rRNA gene sequences are removed? The data is metatranscriptomic sequences. If yes, is all the rRNA removed or just 16S rRNA sequences been removed? Thanks for your time in replying this question.

**Comment by yjiakang** [comment]
Thanks for your quick reply. Another question, is the taxonomy inferred by the 16S rRNA both in metagenomics and metatranscriptomics? If so, the metatranscriptomics that only enriches mRNA is not suitable for this pipeline?

**Comment by fpusan** [comment]
The taxonomy is actually inferred from protein-conding genes, not 16S rRNA genes (though we also classify the 16S sequences, the result is not further used). So SqueezezMeta works perfectly with  mRNAs.

**Comment by yjiakang** [comment]
That is great. Thanks a lot.

**Comment by zhangbenbenchina** [comment]
您好，这个可以跑宏转录组吗？可以指导下如何执行脚本吗？

**Comment by jtamames** [comment]
是的，您可以像分析宏基因组一样分析宏转录组。 查阅手册，看看程序是如何运行的

**Comment by chrismitbiz** [comment]
> The taxonomy is actually inferred from protein-conding genes, not 16S rRNA genes (though we also classify the 16S sequences, the result is not further used). So SqueezezMeta works perfectly with mRNAs.

Hi! I was wondering why 16S rRNA genes are predicted if they are not further used? Thanks!

**Comment by fpusan** [comment]
Hi!
This is mostly because rRNA genes do not assemble reliably from short metagenomics reads. 16S is very conserved, meaning that different organisms will have relatively similar sequences. This can lead to the assembler collapsing several taxa into a single contig.
So while we predict them and do some basic annotation (since it does not take much time) we do not use those 16S rRNA genes for taxonomic annotation.
