### ISSUE TITLE
STABLE VERSION REQUIRED!!!  SQUEEZEMETA

### ISSUE THREAD

**Issue by Michaelijesse** [jtamames/SqueezeMeta#746]
I wish to know which is the stable version of Squeemeta. Already faced many issues. So confirm the STABLE RELEASE OF SQUEEZEMETA.

**Comment by fpusan** [comment]
As in many projects, there is not.

We constantly work on fixing the issues that we find out or are reported by our users. This increases stability.
On the other hand, we also add new features that we deem useful or are requested by our users. This reduces stability.
Sometimes there are errors not related to us directly (eg some conda package breaking, or something related to third party software). I'd say we are quite proactive at tackling those too.

Finally, please note that we do not get paid to do this. Not by our users, nor by our institutions, nor by any funding agency.  Any maintenance/upgrade/troubleshooting that we do here comes at the cost of other things we should be doing in our work (or personal) time. We keep working on this since it is somewhat successful and seems to be helping some people do metagenomics.

Let me reiterate this, in case my point is still not clear. The grant that pays my salary is not related to SqueezeMeta (almost no one funds the maintenance of free bioinformatics software at this scale). I have to do my real job (applying for grants, doing research, mentoring students, writing papers, organizing courses...) **before** I can put work into SqueezeMeta. Which I still manage to do quite regularly.

So if you have any specific problem you would like us to look at, please open a new issue. I would expect that new issue to contain the standard number of exclamation marks and capitalized words, which is to say, zero. Otherwise I hope that you can find a free or commercial solution that does what you need. I now close this issue.
