### ISSUE TITLE
SqueezeMeta stops working in step 18

### ISSUE THREAD

**Issue by eperezv** [jtamames/SqueezeMeta#76]
Hello,

I am running SqueezeMeta with 1 metagenomic sample and got this error message. I have tried to restart the process but it keeps failing. It was running fine until this step and it fails during the analysis of the second bin (the first one seems to work fine). Do you have any clue about the problem?

Thanks a lot,
Eduardo

```
(SqueezeMeta) eduardo@eduardo-PC:/mnt/md0/TETR/SHOTGUN/NFGNB/G/G_T2BC2combined$ restart.pl Sample1 -step 18                            [0 seconds]: STEP18 -> CHECKING BINS: 18.checkM_batch.pl
  Evaluating bins with CheckM (Parks et al 2015, Genome Res 25, 1043-55)

  Reading /home/eduardo/miniconda3/envs/SqueezeMeta/SqueezeMeta/data/alltaxlist.txt
  Looking for DASTool bins in /path/Sample1/results/DAS/Sample1_DASTool_bins
  8 bins found

  Bin 1/8: maxbin.015.fasta.contigs.fa.tax
  Using profile for genus rank : Comamonas
  Bin 2/8: maxbin.018.fasta.contigs.fa.tax
  Using profile for  rank : Stenotrophomonas_maltophilia_group
Error running command:    PATH=/home/eduardo/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin:/home/eduardo/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/pplacer:/home/eduardo/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/hmmer:$PATH /home/eduardo/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/checkm taxon_set  Stenotrophomonas_maltophilia_group /path/Sample1/data/checkm_markers/Stenotrophomonas_maltophilia_group.ms > /dev/null 2>&1 at /home/eduardo/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/18.checkM_batch.pl line 144.
Stopping in STEP18 -> 18.checkM_batch.pl
Died at /home/eduardo/miniconda3/envs/SqueezeMeta/bin/restart.pl line 463.

```

**Comment by jtamames** [comment]
Hello Eduardo
Could you please show me the content of file `maxbin.018.fasta.contigs.fa.tax`?
Thanls!
Javuer

**Comment by eperezv** [comment]
Yes, sure.
Please find it here:
https://drive.google.com/file/d/1gX-lLH0-5mAsJljFHiTvt0dlLrEzolir/view?usp=sharing
Thanks!
Eduardo

**Comment by jtamames** [comment]
Hello
I can see the problem. Could you also send me the intermediate/09<project>contiglog file, and the results/06<project>.fun3.tax.wranks files?
Thanks!

**Comment by eperezv** [comment]
Here they are:
https://drive.google.com/file/d/1Aw7ndpEiwCUvibNz4RUT8RWlxzbn1oME/view?usp=sharing
https://drive.google.com/file/d/1_OoQTrwO2SduLF_3hAxadIq4VNd9-sqL/view?usp=sharing

Cheers,
Eduardo

**Comment by jtamames** [comment]
Ok Eduardo, it looks like a mistake of the creation of the databases, producing some extra annotations that makes it fail. I am looking into it, but for you not having to redo all your results, you can do the following:
In your `09.Sample1.contiglog` file (in the `intermediate` directory), remove all instances of the text string "species ". For example, a line such as:
`spades_59	k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Xanthomonadales;f_Xanthomonadaceae;g_Stenotrophomonas;species n_Stenotrophomonas maltophilia group;s_Stenotrophomonas maltophilia	s	Disparity: 0.000	Genes: 64`

should be transformed into;

`spades_59	k_Bacteria;p_Proteobacteria;c_Gammaproteobacteria;o_Xanthomonadales;f_Xanthomonadaceae;g_Stenotrophomonas;n_Stenotrophomonas maltophilia group;s_Stenotrophomonas maltophilia	s	Disparity: 0.000	Genes: 64`

Then, restart your project from step 17;
`perl restart.pl Sample1 -step 17`

That should do it. In the meantime I will track and fix the bug.
Thanks for reporting this! Let me know if it works.

Best,
Javier

**Comment by jtamames** [comment]
Or, better, change line 115 in the file scripts/18.checkM_batch.pl. Replace:
`if($tax{$ntax} && ($rank ne "n") && ($rank ne "s")) {`

by

`if($tax{$ntax} && ($rank ne "n") && ($rank ne "s") && ($branks{$rank})) {`

and restart from step 18.
Let me know.
Best,

**Comment by eperezv** [comment]
It worked (I tried the last suggestion, by editing the 18.checkM_batch.pl file).
Thanks a lot.
E.

**Comment by jtamames** [comment]
Happy to hear that! I will fix the bug in database creation asap.
Best,

**Comment by eperezv** [comment]
Ok. great. thanks

**Comment by jtamames** [comment]
Fixed issue in script 06, closing

**Comment by eperezv** [comment]
To not open an new issue, is possible to use interleaved files (option --12 in spades)?

**Comment by jtamames** [comment]
If you run SqueezeMeta.pl with the option `--assembly-options "..." `, you can specify the (native) options for the assembler. But in this case it will not work because we are expecting separated pair1 pair2 files for further steps in the pipeline. You must de-interleave them first. Sorry about that.
Best,
Javier

**Comment by eperezv** [comment]
ok. thanks for letting me know.
Cheers,
E.

**Comment by olar785** [comment]
Hi guys,
I'm having a similar issue as Eduardo. Basically, the 18.checkM_batch.pl step dies at line 144, at the first bin it encounters (see below). I checked line 115 in the file scripts/18.checkM_batch.pl and it looks good so it is not the same problem. I have attached the metabat2.184.fa.tax. Thanks for your help! 

[metabat2.184.fa.tax.zip](https://github.com/jtamames/SqueezeMeta/files/4678368/metabat2.184.fa.tax.zip)

  Creating /cluster/home/ollilaroche/Projects/ERA_ICOD_SA/metagenomics/SM/SM_coassembly_profiling_megahit_doublepass/temp/checkm_batch
  Reading /cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/data/alltaxlist.txt
  Looking for DASTool bins in /cluster/home/ollilaroche/Projects/ERA_ICOD_SA/metagenomics/SM/SM_coassembly_profiling_megahit_doublepass/results/DAS/SM_coassembly_profiling_megahit_DASTool_bins
  271 bins found

  Bin 1/271: metabat2.184.fa.tax
  Using profile for domain rank : Bacteria
Error running command:    PATH=/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin:/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/pplacer:/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/hmmer:$PATH /cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/checkm taxon_set domain Bacteria /cluster/home/ollilaroche/Projects/ERA_ICOD_SA/metagenomics/SM/SM_coassembly_profiling_megahit_doublepass/data/checkm_markers/Bacteria.ms > /dev/null 2>&1 at /cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/18.checkM_batch.pl line 144.

**Comment by jtamames** [comment]
Ok, I will check it. Consensus annotation for the bin is phylum Bacteroidetes, so I am puzzled on why it selects the profile for domain bacteria.

**Comment by jtamames** [comment]
Hello
Could you please run the command manually, and tell me the result?
`PATH=/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin:/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/pplacer:/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/hmmer:$PATH /cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/checkm taxon_set domain Bacteria /cluster/home/ollilaroche/Projects/ERA_ICOD_SA/metagenomics/SM/SM_coassembly_profiling_megahit_doublepass/data/checkm_markers/Bacteria.ms`

**Comment by jtamames** [comment]
Also, please uncomment the line 117 in `18.checkM_batch.pl`:
`#   print "$m\t$ntax\t$tax{$ntax}\n";`
and run the script again: `perl 18.checkM_batch.pl <project name>`
And tell me the result, please

**Comment by olar785** [comment]
Hi Javier,
The command you gave me returned the following below. I realised that the DATA_CONFIG was missing and that is because I replaced the lib folder with the newest one on github, as I saw that some changes had been made to few files but did not wanted to re-install the whole program. I copy pasted my backup of DATA_CONFIG and now the scripts run.
However, it seems that 18.checkM_batch.pl is not using the correct rank. For Bin 1 (metabat2.184.fa.tax) it should be using the phylum Bacteroidetes right?

There seems to be a problem with loading the CheckM config file
Please check the permissions / existence / contents of:
/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/checkm/DATA_CONFIG
Traceback (most recent call last):
  File "/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/checkm", line 45, in <module>
    from checkm import main
  File "/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/main.py", line 25, in <module>
    from checkm.defaultValues import DefaultValues
  File "/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/defaultValues.py", line 26, in <module>
    class DefaultValues():
  File "/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/defaultValues.py", line 29, in DefaultValues
    __DBM = DBManager()
  File "/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/checkmData.py", line 103, in __init__
    self.config = DBConfig()  # load inbuilt configuration
  File "/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/checkmData.py", line 40, in __init__
    self.values = self.getConfig()
  File "/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/../lib/checkm/checkmData.py", line 48, in getConfig
    with open(self.configFile, 'r') as local_config:
FileNotFoundError: [Errno 2] No such file or directory: '/cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/checkm/DATA_CONFIG'

And this is a snapshot of the output of 18.checkM_batch.pl now:
  Reading /cluster/home/ollilaroche/miniconda3/envs/SqueezeMeta/SqueezeMeta/data/alltaxlist.txt
  Looking for DASTool bins in /cluster/home/ollilaroche/Projects/ERA_ICOD_SA/metagenomics/SM/SM_coassembly_profiling_megahit_doublepass/results/DAS/SM_coassembly_profiling_megahit_DASTool_bins
  271 bins found

  Bin 1/271: metabat2.184.fa.tax
metabat2.184.fa.tax	Bacteria	superkingdom
  Using profile for domain rank : Bacteria

**Comment by jtamames** [comment]
Hello
Good to know that it is working now.
Regarding the other issue, I am sending to you a new 18.checkm.pl script. It is the same one but I put several traces in it
[18.checkM_batch.pl.gz](https://github.com/jtamames/SqueezeMeta/files/4681346/18.checkM_batch.pl.gz)
 to let us know what is going on. Could you please run this one in the same way than before, and paste the result here?
Thanks!

**Comment by olar785** [comment]
Thanks,
Below is the results.

  Bin 1/271: metabat2.184.fa.tax
Reading consensus from /cluster/home/ollilaroche/Projects/ERA_ICOD_SA/metagenomics/SM/SM_coassembly_profiling_megahit_doublepass/results/DAS/SM_coassembly_profiling_megahit_DASTool_bins/metabat2.184.fa.tax
  Consensus: k_Bacteria;n_FCB group;n_Bacteroidetes/Chlorobi group;p_Bacteroidetes
  Size:4964814
    Full tax: p_Bacteroidetes
   Rank: p; Tax: Bacteroidetes
    phylum
    Full tax: n_Bacteroidetes/Chlorobi group
   Rank: n; Tax: Bacteroidetes/Chlorobi group
   no rank 
    Full tax: n_FCB group
   Rank: n; Tax: FCB group
   no rank 
    Full tax: k_Bacteria
   Rank: k; Tax: Bacteria
   superkingdom domain
   To list: metabat2.184.fa.tax	Bacteria	superkingdom
  Using profile for domain rank : Bacteria

**Comment by jtamames** [comment]
Ok, now try this one. Let it run for a bunch of bins (ten, for instance), and then send me the result.
Thanks

[18.checkM_batch.pl.gz](https://github.com/jtamames/SqueezeMeta/files/4681601/18.checkM_batch.pl.gz)

**Comment by jtamames** [comment]
I found the problem. A silly thing, we are reading a list of NCBI's taxonomy where some taxa are listed as "Bacteroidetes <phylum>", to specify the correct rank when it can be confused with some other. And it does not match the SqueezeMeta taxonomy that will be just "Bacteroidetes". So, it will potentially affect to bins belonging to taxa listed like that (with the "<rank>" notation) in NCBI's taxonomy. It is not a critical mistake, since the bin will be evaluated with the profile for the upper lever (Bacteria in your case), but it will be less precise.

So, you can skip the test I asked you for before, and  try this version of the script. It is a clean one, no extra traces. If it works well for you I will update the repo.

Thanks for helping us with this!

[18.checkM_batch.pl.gz](https://github.com/jtamames/SqueezeMeta/files/4681777/18.checkM_batch.pl.gz)

**Comment by olar785** [comment]
Ok thanks. Will give it a try and let you know how it goes.

**Comment by olar785** [comment]
Hi Javier,
Just wanted to tell you that the new script worked like a charm, thanks!
There is something that I wanted to share with you though, might be worth opening a new issue, not sure yet. I ran the pipeline using the default annotation options and than, seing I had very low mapping rate for some samples, I decided to re-run the annotation with the --doublepass option. What I find suspicious is that the mapping rate in both 10.SM_coassembly_profiling_megahit.mappingstat files are exactly the same. Should there not be a little improvement in mapping rate with --doublepass or am I misunderstanding something?

**Comment by jtamames** [comment]
Hello! It´s great to know that it worked! Did you check that the Bacteroidetes bin is now using the Bacteroidetes profile, not the one of Bacteria as before?

What the double pass is doing is predict ORFs in contigs first using Prodigal (gene prediction), and then Diamond Blastx for complete the annotation. That is, finding ORFs that Prodigal missed or correcting wrong gene predictions. But notice that the set of contigs remains exactly the same. The mapping refers to the percentage of reads that can be aligned to the contigs. Therefore, the blastx step is not influencing the mapping percentage, since you are working with the same set of reads and contigs. and consequently it is correct that the percentage is exactly the same. But you should see an improvement in the number of ORFs, that must be way higher using Blastx. You can take a look the 22*stats file to check that.

Best,
Javier

**Comment by olar785** [comment]
Hi Javier,
Yes, as far as I can tell the correct profile is now used for each bin.
Thanks for your explanation, makes complete sense :)
Best,
Olivier
