### ISSUE TITLE
default minimum contig length assembly

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#78]
Hi,

I noticed the default minimum length of contigs for the assembly is set at 200. May I ask what the underlying reason is that this is set so low? And not at 1000 for example? Just wondering if and why more users would use a default value of 200 instead of 1000?

Best,

Sam

**Comment by jtamames** [comment]
Hello Sam
You can set the minimum contig length using the -c option when invoking SqueezeMeta. It is set to 200 to consider all contigs provided by the assembler, but indeed this will produce a very high number of contigs in large metagenomes. In these case you can set it to 1000 using -c 1000.
Best,
Javier

**Comment by slambrechts** [comment]
Hi Javier,

What I mean is don't people usually set this value at 1000 or higher when the goal is to assemble complete clean genomes? In other words, I was curious as to why you set 200 as the default value? I can imagine if you want to look at SNPs and you want to search every possible base alteration then 300 or 200 might be usefull. But wouldn't a default value of 1000 suit more/most people?

Best,
Sam

**Comment by fpusan** [comment]
Hi,

Our primary aim is not necessarily to assemble complete clean genomes (which IMO is generally not possible in metagenomics) but to extract the maximum possible information from the metagenomes, and 200 is for example the default cutoff of Megahit. Using a higher cutoff might not affect the high-coverage genomes in your sample, but you might start losing information from the less abundant genomes.

Of course, users with low-complexity samples (or single genomes) can use higher cutoffs, and will not lose much information (then again, they won't gain a lot of performance either, because most of the contigs will be high-length regardless). Our criterion here was to provide as much information as we can by default, and leave users room to decide if they need it or not.

**Comment by slambrechts** [comment]
Hi,

Thank you for the information, it makes sense now!

Best,

Sam
