### ISSUE TITLE
How to group samples of the same treatments?

### ISSUE THREAD

**Issue by DioufMouss0** [jtamames/SqueezeMeta#788]
Hello 
I am working with metagenomics data that was isolated from from plant under two different treatment.
I am using squeezemeta for the analysis and I want to further proceed with SQMtools for downstream analysis in R.
Therefore as it is possible in 16s metabarcoding I would like to know if there is anyway to group samples replicates from same treatments.

Thanks

**Comment by fpusan** [comment]
Yes and no. SQMtools does not store any metadata on your samples so each sample is treated individually. However you can just load a separate metadata table indicating the group to which each sample belonged, and use that to feed whatever statistical method you plan on using.

**Comment by DioufMouss0** [comment]
Hello Professor, I have read the manual but did't see a part on how to do that.
Could you please help with it?

Thanks

**Comment by fpusan** [comment]
This is not in the manual because this is not part of SqueezeMeta per se. SqueezeMeta doesn't keep track on how your samples are grouped.
You would do this in different ways depending on the R package you want to use to further analyze your results.
In our [wiki](https://github.com/jtamames/SqueezeMeta/wiki/Using-R-to-analyze-your-SQM-results) we show an example in which we do this for `DESeq2` and also the `exportPathways` function from `SQMtools`, grouping samples based on their country of origin. But this is really R/biostatistics support, rather than SqueezeMeta-specific support.
