### ISSUE TITLE
--euk flag

### ISSUE THREAD

**Issue by slambrechts** [jtamames/SqueezeMeta#79]
Hello,

Do I skip eukaryotic annotation by specifying the `--euk` flag, or do I enable it? Not sure how I should interpret the "drop" in the "--euk : Drop identity filters for eukaryotic annotation" sentence in the manual.

Best,
Sam

**Comment by fpusan** [comment]
Hi,

This is actually explained briefly in the release notes, and in the PDF manual, but it is not very easy to find, so until we fix the ReadMe I'll explain it here.

By default, SqueezeMeta applies Luo et al. (2014) identity cutoffs in order to assign an ORF to a given taxonomic rank (see explanation of the LCA algorithm in the PDF manual). This means that for example, a gene whose common ancestor is _E. coli_ but in which the hits to the reference have 45% similarity will only get classified as _Proteobacteria_ (not as _E. coli._) because the similarity is not enough for a species-level annotation.

This results in highly conservative, but also very trustworthy taxonomic annotations. If SqueezeMeta says that something is annotated at the genus or species level _it really means it_.

However, these filters does not work so well for eukaryotes, resulting in too few annotations. We believe that the main reasons are the following:
- Those filters were calculated using prokaryotic genomes, and might not be valid in eukaryotes.
- Eukaryotes are poorly represented in the databases, leading to lower similarities on average.

The `--euk` flag will apply Luo et al.'s cutoff for annotation only to prokaryotic genes, and use a normal LCA algorithm with no cutoff for the eukaryotes. This still gives a very robust taxonomy for prokaryotes, while still providing some information on what kind of eukaryotes might be in the sample.

If you are using the SQMtools R package for analyzing your results, you can also control this behaviour when loading the data with the `loadSQM` function. This way you don't have to repeat the whole project if you did not apply the `--euk` parameter when running SqueezeMeta. The way to do it would be 

```
library(SQMtools)
proj = loadSQM("/path/to/my/project", tax_mode = "prokfilter")
```

Best,

Fernando

**Comment by slambrechts** [comment]
Hi Fernando,

I read about that in the manual, but I did not realize the --euk flag had to do with this. All clear now, thanks

Best,
Sam
