### ISSUE TITLE
Stopping in STEP4 -> 04.rundiamond.pl

### ISSUE THREAD

**Issue by Biotrinf** [jtamames/SqueezeMeta#845]
Hi,
I have faced the "Stopping in STEP4 -> 04.rundiamond.pl Program finished abnormally" error.

I could not understand the problem. I have already checked the syslog file, but there is no extraordinary situation. I have attached the file as well. Is there a problem with installing the database on Windows and running squeezeMeta via WSL2? Also, I have 32 GB RAM and enough hard drive space.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/15430884/syslog.zip)

Is there any way to continue from the program is killed?

**Comment by fpusan** [comment]
SqueezeMeta runs in WSL2, but you should have your databases in the WSL2 partition (rather than the windows partition), see #695.

Still, it should work with the database in the windows partition (just become very slow at times). DIAMOND dying is usually due to lack of memory. What's the output in `/home/bioinf/mku/temp/diamond.nr.log`?

Also even if you have 32Gb RAM it may not all be available to WSL2 (e.g. https://superuser.com/questions/1707758/wsl-2-does-not-have-all-memory-available-to-it). In fact, SqueezeMeta seems to be only seeing 15 Gb of free RAM. Are you running other things in parallel.

Anyways I would edit the `home/bioinf/mku/SqueezeMeta_conf.pl` file and change the value of `$blocksize` to 0.5 (so that DIAMOND uses less memory) and then restart the run `SqueezeMeta.pl --restart -p mku`, hopefully that will fix it. You can also add the parameter `-b 0.5` when starting runs in the future to control this.

**Comment by Biotrinf** [comment]
First of all thanks for your support. 

I have changed all the folder locations into the WSL2 partition. However, the problem was not terminated.  

Then, I changed the WSL2 RAM setting so the WSL2 could use the 24GB capacity of the RAM (before, it could not use more than 16GB half of the current capacity). Finally, the program worked, and the problem was solved.

**Comment by fpusan** [comment]
Glad to hear. Closing!
