### ISSUE TITLE
Problem to load SQM project

### ISSUE THREAD

**Issue by inej90** [jtamames/SqueezeMeta#848]
Dear Fernando y Javier,

I run SQM using nanopore sequences and Flye to coassembly.

I obtained all the files of this project. But when I want to load it in R with SQMtools. I have the following message:

![Captura de pantalla 2024-06-05 191247](https://github.com/jtamames/SqueezeMeta/assets/154340100/8cfb40e0-210c-4209-9cd2-e0871ca6e2a8)

I tried to change the path of the project and put it in another one, but I obtained again an error:

![Captura de pantalla 2024-06-05 192437](https://github.com/jtamames/SqueezeMeta/assets/154340100/c6ae9ec6-deca-4974-8147-970feb2862ff)

Am I doing something wrong?

Thank you in advance.

**Comment by fpusan** [comment]
Hi!

It would seem like you are running out of memory while trying to load the project.
Is this maybe the access node of a computing cluster? or an interactive job requesting too little memory?

The second error happens because of the way you copied things. You should run `sqm2tables.py /path/to/project /path/to/project/results/tables` in the same computer in which you ran the pipeline, before copying the results to a different place.

**Comment by inej90** [comment]
Hi all,

I have been able to load tables (after loading them in the cluster) using loadSQMlite and it works.

Thank you very much for your help.

**Comment by fpusan** [comment]
Glad to hear It works. Let us know if you need more help
