### ISSUE TITLE
Taxonomy abundance from SQM object

### ISSUE THREAD

**Issue by Vincev454** [jtamames/SqueezeMeta#854]
Dear authors,

I'm a bit confused with the different taxonomy abundances calculated by SqueezeMeta : for instance when using : "genus_tax=Hadza$taxa$genus$abund", do you get the sum of abundances indentified in ORFs, contigs, and bins for each genus?

Best,
Vince

**Comment by fpusan** [comment]
When you load a project the taxonomy abundances will be derived from the contig-level annotations.
This will also be the case when doing subsets, except for `subsetFun`, in which the taxonomy will be derived from ORF-level annotations (since this function subsets individual ORFs rather than whole contigs).
Currently we don't use bins as a source of taxonomy, but I am open to add this feature if there is interest and I find some spare time.
