### ISSUE TITLE
Projects cannot been loaded in SQMtools

### ISSUE THREAD

**Issue by Selucote82** [jtamames/SqueezeMeta#884]
Dear SqueezeMeta developers, here I'm again!

It's been impossible to load a project in RStudio in MacOSX after loading SQMtools. I tried with sq2zip.py after ending the SM pipe,  and also deleting the "tables" directory and launching sqm2tables.py. 

Afterwards, I tried to load the .zip project in mi MacOS laptop using RStudio and was impossible to load:

- PN4=loadSQM("~/Desktop/Genomics/Nanopore_RawData/PN4/PN4.zip") 
 R Session Aborted. R encountered a fatal error. The session was terminated.

-PN4=loadSQMlite("~/Desktop/Genomics/Nanopore_RawData/PN4/PN4.zip")
Error in loadSQMlite("~/Desktop/Genomics/Nanopore_RawData/PN4/PN4.zip") :
 Directory "~/Desktop/Genomics/Nanopore_RawData/PN4/PN4.zip" does not seem to contain valid SqueezeMeta tables 
In this one trying sqm2tables.py too.

- Unzipping the PN4.zip in PN4_project directory created PN4=loadSQM("~/Desktop/Genomics/Nanopore_RawData/PN4/PN4_project")
An error occurred while running sqm2tables.py

Any clue with this?

Thank you!

**Comment by fpusan** [comment]
`PN4=loadSQM("~/Desktop/Genomics/Nanopore_RawData/PN4/PN4.zip")` should be the right way to do it, but we've been having issues with some zip files in particular. Those can be traced back to limitations/bugs on how R handles zip files, I've looked for alternatives but haven't come to a solution yet. The issue normally raises an error when loading the project, instead of killing the R session, but maybe it's different in Mac...

Does `PN4.zip` still contain the tables? (i.e. it is the original zip file produced by `sqm2zip.py`). If so, unzipping it should work. See detailed instructions in #755

**Comment by fpusan** [comment]
Glad to hear, and sorry for the inconvenience!
