### ISSUE TITLE
Error in loading SQM - version conflict

### ISSUE THREAD

**Issue by Whitehouse2610** [jtamames/SqueezeMeta#885]
I am having the following error in a newly created SQM_output file using SqueezeMeta 1.6.5. The current version of SQMtools I am using is v1.6.3. 

> trail_01 = loadSQM('R_data/project_data')
Generating tabular outputs for project in R_data/project_data
Error in loadSQM("R_data/project_data") : 
  An error occurred while running sqm2tables.py
In addition: Warning message:
In loadSQM("R_data/project_data") :
  Your project was created with SqueezeMeta v1.6.5, while this is SQMtools v1.6.3. You can ignore this message if things are working fine for you, but if you experience any issue consider using the right version of SQMtools for this project

I look forward to hearing back. @dutchscientist

**Comment by dutchscientist** [comment]
To add to this (I am supporting Whitehouse2610), we don't see any download location for SQMtools 1.6.5. As we are just starting to run a significant number of samples for a project, it is important to know whether we can run them on SqueezeMeta 1.6.5 or have to revert to 1.6.3 because of the downstream analysis compatibility. Thanks :)

**Comment by dutchscientist** [comment]
Thank you. We indeed run SqueezeMeta on our more powerful computers, and users then analyse on their own computer. We'll try this out :)

**Comment by fpusan** [comment]
That should work! Closing this for now, let me know if you run into other issues
