### ISSUE TITLE
Stop in STEP6

### ISSUE THREAD

**Issue by kds2923** [jtamames/SqueezeMeta#9]
Hello,

When I tested with test data, Squeeze meta was aborted in STEP6. (I used 0.4.2 version however same abort in 0.4.1 version)

[5 hours, 54 minutes, 32 seconds]: STEP6 -> TAXONOMIC ASSIGNMENT: 06.lca.pl
Tax assignment done in /Tools/SqueezeMeta/0.4.2/SqueezeMeta/test_run/results/06.test_run.fun3.tax but no results found. Aborting
Stopping in STEP6 -> 06.lca.pl

How can I pass the STEP6? 

Tahnks,

**Comment by fpusan** [comment]
Hello!
* What are your system specifications?
* The file `Tools/SqueezeMeta/test_run/results/04.test_run.nr.diamond` should be around 360Mb if you're running SqueezeMeta with the test data. Is it that large for you?
* The file `<path_to_your_database>/LCA_tax/taxid.db` should be around 26 Gb. Is it that large for you?
* If everything seems right, please try the following:
    * Open the file SqueezeMeta/scripts/06.lca.pl
    * In line 34, change "my $verbose=0;" to "my $verbose=1;"
    * Run again step 6 with `perl /Tools/SqueezeMeta/0.4.2/SqueezeMeta/06.lca.pl /Tools/SqueezeMeta/0.4.2/SqueezeMeta/test_run`
    * Capture the output and send us the first 1000 lines.

**Comment by kds2923** [comment]
Oh, my taxid.db file size was 12kb. And parents.db file size was 12kb too.

So, I checked the sql input files. And I found that some commands of these input file (taxid.sql and parents.sql) were blocked with '--'.
When it was deleted, it was confirmed that the database was created normally.
I wonder if there is a reason why it is blocked.

Thanks,

**Comment by fpusan** [comment]
The database import is managed directly by the make_databases.pl script, so It shouldn't be necessary to run it manually. I wonder why it didn't work for you.

Anyways, please note that SqueezeMeta is currently supported only for Ubuntu 14+ and CentOS7. Some things (like the automated database building script) might not work as expected in CentOS6... let us know if it works for you.

Anyways, I'm glad the issue was solved. For next version, we'll switch to providing a pre-compiled database, which should help with problems like this.

Best,

Fernando

**Comment by fpusan** [comment]
Closed, as it should be solved with the switch to pre-compiled databases in v0.4.3.
